# Generated by Django 5.2.3 on 2026-08-22 07:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_referralledger'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Exercise ID (e.g. EXE-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Barbell Back Squat', max_length=255)),
                ('category', models.CharField(choices=[('Strength', 'Strength Training'), ('Pilates', 'Reformer & Mat Pilates'), ('Cardio', 'Cardiovascular'), ('Mobility', 'Mobility & Flexibility'), ('Core', 'Core Stability'), ('HIIT', 'HIIT / Conditioning')], default='Strength', max_length=32)),
                ('primary_muscle', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Quadriceps', 'Quadriceps'), ('Hamstrings', 'Hamstrings'), ('Glutes', 'Glutes'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Core', 'Core'), ('Full Body', 'Full Body')], default='Full Body', max_length=32)),
                ('equipment', models.CharField(default='Barbell', max_length=64)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=32)),
                ('movement_pattern', models.CharField(choices=[('Squat', 'Squat'), ('Hinge', 'Hinge'), ('Push', 'Push'), ('Pull', 'Pull'), ('Lunge', 'Lunge'), ('Carry', 'Carry'), ('Rotation', 'Rotation'), ('Isometric', 'Isometric')], default='Squat', max_length=32)),
                ('instructions', models.TextField(help_text='Step-by-step technique breakdown')),
                ('video_url', models.URLField(blank=True, default='')),
                ('contraindications', models.TextField(blank=True, default='', help_text='Injuries or conditions to avoid this movement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'coaching_exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Assessment ID (e.g. ASM-001)', max_length=64, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('assessment_type', models.CharField(choices=[('Initial', 'Initial Assessment'), ('Periodic', 'Periodic Check-in'), ('Mobility', 'Mobility & Posture'), ('Post-Program', 'Post-Program Evaluation')], default='Initial', max_length=32)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('muscle_mass_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('squat_1rm_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bench_1rm_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deadlift_1rm_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('plank_hold_sec', models.IntegerField(blank=True, null=True)),
                ('mobility_score', models.IntegerField(default=70, help_text='Mobility / Flexibility score (0-100)')),
                ('overall_fitness_score', models.IntegerField(default=75, help_text='Calculated overall score (0-100)')),
                ('posture_notes', models.TextField(blank=True, default='')),
                ('trainer_summary', models.TextField(blank=True, default='')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'coaching_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Food ID (e.g. FOD-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Paneer Tikka / Dal Tadka', max_length=255)),
                ('diet_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan'), ('Jain', 'Jain'), ('Regional Indian', 'Regional Indian Diet')], default='Vegetarian', max_length=32)),
                ('serving_unit', models.CharField(default='100g', max_length=64)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fiber_g', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'coaching_food_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Nutrition Plan ID (e.g. NUT-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Lean Muscle & High-Protein Indian Diet', max_length=255)),
                ('diet_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegan', 'Vegan'), ('Jain', 'Jain'), ('Regional Indian', 'Regional Indian Diet')], default='Vegetarian', max_length=32)),
                ('daily_calorie_target', models.IntegerField(default=2200)),
                ('protein_target_g', models.IntegerField(default=150)),
                ('carbs_target_g', models.IntegerField(default=220)),
                ('fat_target_g', models.IntegerField(default=60)),
                ('hydration_liters', models.DecimalField(decimal_places=1, default=3.5, max_digits=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_nutrition_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Mid-Morning', 'Mid-Morning Snack'), ('Lunch', 'Lunch'), ('Evening Snack', 'Evening Snack / Pre-Workout'), ('Dinner', 'Dinner')], default='Breakfast', max_length=64)),
                ('quantity', models.CharField(default='1 serving', max_length=64)),
                ('calculated_calories', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coaching.fooditem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='coaching.nutritionplan')),
            ],
            options={
                'db_table': 'coaching_meal_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_name', models.CharField(max_length=128)),
                ('day_order', models.IntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'coaching_workout_days',
                'ordering': ['day_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=1)),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.CharField(default='8-12', max_length=32)),
                ('rest_seconds', models.IntegerField(default=60)),
                ('tempo', models.CharField(blank=True, default='3-0-1-0', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.exercise')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coaching.workoutday')),
            ],
            options={
                'db_table': 'coaching_workout_day_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Program ID (e.g. PRG-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. 12-Week Hypertrophy & Strength Program', max_length=255)),
                ('goal', models.CharField(blank=True, default='', max_length=255)),
                ('duration_weeks', models.IntegerField(default=12)),
                ('days_per_week', models.IntegerField(default=4)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_programs', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workout_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coaching_workout_programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='coaching.workoutprogram'),
        ),
    ]
