# Generated by Django 5.2.3 on 2026-08-22 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessassessment',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
