# Generated by Django 5.2.3 on 2026-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', help_text='Emergency contact name and phone number', max_length=255),
        ),
    ]
