# Generated by Django 5.2.3 on 2026-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_marketplaceapp_historicalusagesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='login_tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='remove_watermark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='support_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='favicon_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='logo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
