# Generated by Django 5.2.3 on 2026-08-21 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Unique Member ID (e.g. MEM-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expiring', 'Expiring'), ('Frozen', 'Frozen'), ('Lapsed', 'Lapsed'), ('Cancelled', 'Cancelled')], default='Active', max_length=32)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', help_text='Churn risk indicator', max_length=16)),
                ('health_score', models.IntegerField(default=85, help_text='Health score 0-100')),
                ('performance_score', models.IntegerField(default=80, help_text='Strength/performance score 0-100')),
                ('fitness_goal', models.CharField(blank=True, default='', help_text='Primary fitness objective', max_length=255)),
                ('from_lead_id', models.CharField(blank=True, default='', help_text='Original Lead ID if converted through sales pipeline', max_length=64)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(help_text='Home studio / branch location', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.location')),
                ('primary_coach', models.ForeignKey(blank=True, help_text='Assigned trainer or fitness coach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_members', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('QR Code', 'QR Code'), ('Biometric', 'Biometric'), ('Front Desk', 'Front Desk'), ('App', 'App')], default='Front Desk', max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.member')),
            ],
            options={
                'db_table': 'member_attendance',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Plan ID (e.g. PLN-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plan name (e.g. 12-Week Strength Transformation)', max_length=255)),
                ('category', models.CharField(choices=[('Membership', 'Membership'), ('Personal Training', 'Personal Training'), ('Pilates', 'Pilates'), ('Nutrition', 'Nutrition'), ('All-Access Elite', 'All-Access Elite')], default='Membership', max_length=64)),
                ('duration_months', models.IntegerField(default=1, help_text='Duration in months')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sessions', models.IntegerField(blank=True, help_text='Number of sessions included (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'membership_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Subscription ID (e.g. SUB-001)', max_length=64, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sessions_remaining', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Frozen', 'Frozen'), ('Cancelled', 'Cancelled')], default='Active', max_length=32)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='members.membershipplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'member_subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
