# Generated by Django 5.2.3 on 2026-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
