# Generated by Django 5.2.3 on 2026-08-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_joined_at'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Ledger ID (e.g. REF-001)', max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Referral Signup', 'Referral Signup'), ('Renewal Bonus', 'Renewal Bonus'), ('Birthday Reward', 'Birthday Reward'), ('Points Redemption', 'Points Redemption')], default='Referral Signup', max_length=32)),
                ('points', models.IntegerField(help_text='Positive for points earned, negative for redemptions')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_entries', to='members.member')),
                ('referred_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_entries', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'member_referral_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
