# Generated by Django 5.2.3 on 2026-08-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_referralledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=16),
        ),
    ]
