# Generated by Django 5.2.3 on 2026-08-21 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Unique Lead Identifier (e.g. LED-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Instagram', 'Instagram'), ('Referral', 'Referral'), ('Walk-in', 'Walk-in'), ('Meta Ads', 'Meta Ads'), ('Google Ads', 'Google Ads'), ('Phone Inquiry', 'Phone Inquiry'), ('Corporate', 'Corporate')], default='Website', max_length=64)),
                ('interested_service', models.CharField(default='Strength Training', help_text='Primary fitness service interested in (e.g. Strength, Pilates, PT)', max_length=128)),
                ('goal', models.CharField(blank=True, default='', help_text='Customer primary fitness goal (e.g. Weight Loss, Muscle Gain)', max_length=255)),
                ('stage', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Trial Booked', 'Trial Booked'), ('Trial Attended', 'Trial Attended'), ('Offer Sent', 'Offer Sent'), ('Negotiation', 'Negotiation'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', help_text='Sales pipeline stage', max_length=32)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')], default='Open', help_text='Overall status: Open, Won, or Lost', max_length=16)),
                ('score', models.IntegerField(default=50, help_text='AI / Lead Quality score (0 to 100)')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, help_text='Customer monthly or package budget', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('trial_date', models.DateTimeField(blank=True, help_text='Scheduled trial session date/time', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Sales rep or trainer assigned to manage this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location / Studio branch this lead is interested in', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Trial', 'Trial'), ('Note', 'Note'), ('Stage Change', 'Stage Change')], default='Note', max_length=32)),
                ('summary', models.TextField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'crm_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
