# Generated by Django 5.2.3 on 2026-08-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(help_text='Tenant identifier (e.g. TEN-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand or gym name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(help_text='Location identifier (e.g. LOC-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Studio or branch name', max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_locations',
                'ordering': ['city', 'name'],
            },
        ),
    ]
