# Generated by Django 5.2.3 on 2026-08-25 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPlan',
            fields=[
                ('id', models.CharField(help_text='e.g. PLAN-STARTER', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('max_locations', models.IntegerField(default=1)),
                ('max_members', models.IntegerField(default=500)),
                ('max_trainers', models.IntegerField(default=10)),
                ('ai_voice_minutes', models.IntegerField(default=100)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_plans',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='branding', serialize=False, to='tenants.tenant')),
                ('app_name', models.CharField(default='PerformanceOS', max_length=128)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('favicon_url', models.URLField(blank=True, default='')),
                ('primary_color', models.CharField(default='#0f766e', help_text='Primary Brand Hex Color', max_length=32)),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent Hex Color', max_length=32)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('cname_verified', models.BooleanField(default=False)),
                ('email_footer', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_branding',
            },
        ),
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usage', serialize=False, to='tenants.tenant')),
                ('active_members_count', models.IntegerField(default=0)),
                ('locations_count', models.IntegerField(default=1)),
                ('trainers_count', models.IntegerField(default=0)),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('ai_minutes_used', models.IntegerField(default=0)),
                ('api_requests_count', models.BigIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tenant_usage',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='location',
            name='operating_hours',
            field=models.CharField(default='06:00 - 22:00', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_locations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_members',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Trial', 'Trial'), ('Expired', 'Expired')], default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tier',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Enterprise', 'Enterprise')], default='Growth', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='URL-friendly slug / subdomain', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='tenants.platformplan'),
        ),
    ]
