# Generated by Django 5.2.3 on 2026-09-04 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_platformplan_tenantbranding_tenantusage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceApp',
            fields=[
                ('id', models.CharField(help_text='e.g. app-sarvam', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('AI & Voice', 'AI & Voice'), ('Payments', 'Payments'), ('Messaging', 'Messaging'), ('Access Control', 'Access Control'), ('Accounting', 'Accounting')], default='AI & Voice', max_length=64)),
                ('icon_text', models.CharField(default='AP', max_length=8)),
                ('developer', models.CharField(default='PerformanceOS Verified', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('required_tier', models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Enterprise', 'Enterprise')], default='Starter', max_length=32)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketplace_apps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('members_count', models.IntegerField(default=0)),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('ai_minutes_used', models.IntegerField(default=0)),
                ('api_requests_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_usage_snapshots',
                'ordering': ['-snapshot_date'],
                'unique_together': {('tenant', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='TenantAppInstallation',
            fields=[
                ('id', models.CharField(help_text='e.g. INST-001', max_length=64, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('config_data', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='tenants.marketplaceapp')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_installations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_app_installations',
                'ordering': ['-installed_at'],
                'unique_together': {('tenant', 'app')},
            },
        ),
    ]
