# Generated by Django 5.2.3 on 2026-08-25 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_platformplan_tenantbranding_tenantusage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='e.g. KEY-001', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Mobile App Gateway or Website Form', max_length=128)),
                ('key_prefix', models.CharField(default='pk_live_', max_length=16)),
                ('key_hash', models.CharField(max_length=255)),
                ('permissions_scope', models.JSONField(blank=True, default=list)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('EXPORT', 'EXPORT'), ('IMPERSONATE', 'IMPERSONATE')], default='UPDATE', max_length=32)),
                ('module', models.CharField(help_text='e.g. CRM, Members, Finance, Users', max_length=64)),
                ('entity_type', models.CharField(help_text='e.g. Member, Invoice, Lead', max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('diff_payload', models.JSONField(blank=True, default=dict, help_text='Previous vs New values diff')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='e.g. FORM-PARQ', max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('fields_schema', models.JSONField(default=list, help_text='List of field definitions (label, type, required, options)')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'custom_forms',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enforce_mfa', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('password_min_length', models.IntegerField(default=8)),
                ('require_special_character', models.BooleanField(default=True)),
                ('max_failed_attempts_lockout', models.IntegerField(default=5)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'security_policies',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='e.g. SVC-001', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Fitness', 'Fitness'), ('Personal Training', 'Personal Training'), ('Pilates', 'Pilates'), ('Yoga', 'Yoga'), ('Nutrition', 'Nutrition'), ('Wellness & Spa', 'Wellness & Spa'), ('Physiotherapy', 'Physiotherapy'), ('Recovery', 'Recovery')], default='Fitness', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('duration_minutes', models.IntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.IntegerField(default=1, help_text='Max concurrent clients')),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, help_text='Specific location or all locations if null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('tax_rate_gst', models.DecimalField(decimal_places=2, default=18.0, help_text='GST / VAT Percentage', max_digits=5)),
                ('tax_id_number', models.CharField(blank=True, default='', help_text='GSTIN / Tax ID', max_length=64)),
                ('booking_cancellation_window_hours', models.IntegerField(default=12, help_text='Hours before class when cancellation is penalty-free')),
                ('late_cancellation_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('allow_guest_passes', models.BooleanField(default=True)),
                ('guest_passes_per_month', models.IntegerField(default=2)),
                ('membership_grace_period_days', models.IntegerField(default=7)),
                ('allow_member_freeze', models.BooleanField(default=True)),
                ('max_freeze_days_per_year', models.IntegerField(default=60)),
                ('business_open_time', models.CharField(default='06:00', max_length=16)),
                ('business_close_time', models.CharField(default='22:00', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_settings',
            },
        ),
    ]
