# Generated by Django 5.2.3 on 2026-08-25 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_platformplan_tenantbranding_tenantusage_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.CharField(help_text='e.g. PERM-CRM-LEADS-EDIT', max_length=64, primary_key=True, serialize=False)),
                ('module', models.CharField(help_text='e.g. CRM, Members, Operations, Finance, Platform, Administration', max_length=64)),
                ('action', models.CharField(help_text='e.g. view, create, edit, delete, export', max_length=32)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'action'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Invited', 'Invited'), ('Suspended', 'Suspended')], default='Active', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Studio Manager', 'Studio Manager'), ('Operations Manager', 'Operations Manager'), ('Sales', 'Sales'), ('Front Desk', 'Front Desk'), ('Trainer', 'Trainer'), ('Pilates Instructor', 'Pilates Instructor'), ('Nutrition Coach', 'Nutrition Coach'), ('Finance', 'Finance'), ('Support', 'Support'), ('Member', 'Member')], default='Admin', help_text='User role in the system', max_length=64),
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.CharField(help_text='e.g. ROLE-ADMIN', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='users.roledefinition'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='users.permissiondefinition')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.roledefinition')),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
