# Generated by Django 5.2.3 on 2026-08-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_member_joined_at'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Trainer ID (e.g. TRN-001)', max_length=64, primary_key=True, serialize=False)),
                ('specialization', models.CharField(help_text='e.g. Strength & Conditioning, Reformer Pilates, Hypertrophy', max_length=128)),
                ('certification', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('pt_hourly_rate', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainers',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Class ID (e.g. CLS-001)', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Morning Strength Circuit', max_length=255)),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Pilates', 'Pilates'), ('HIIT', 'HIIT'), ('Yoga', 'Yoga'), ('Conditioning', 'Conditioning')], default='Strength', max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_capacity', models.IntegerField(default=15)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tenants.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='operations.trainer')),
            ],
            options={
                'db_table': 'fitness_classes',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(help_text='Booking ID (e.g. BKG-001)', max_length=64, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('Class', 'Class'), ('Personal Training', 'Personal Training'), ('Pilates', 'Pilates'), ('Assessment', 'Assessment')], default='Personal Training', max_length=32)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], default='Confirmed', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tenants.location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='members.member')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('fitness_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='operations.fitnessclass')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_bookings', to='operations.trainer')),
            ],
            options={
                'db_table': 'ops_bookings',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
