# Generated by Django 5.2.3 on 2026-09-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantbranding_login_tagline_and_more'),
        ('users', '0002_permissiondefinition_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiondefinition',
            name='scope',
            field=models.CharField(choices=[('platform', 'Platform Scope'), ('tenant', 'Tenant Scope')], default='tenant', max_length=32),
        ),
        migrations.AddField(
            model_name='roledefinition',
            name='scope',
            field=models.CharField(choices=[('platform', 'Platform Scope'), ('tenant', 'Tenant Scope')], default='tenant', max_length=32),
        ),
        migrations.AlterField(
            model_name='permissiondefinition',
            name='action',
            field=models.CharField(help_text='e.g. view, create, edit, delete, manage, export', max_length=32),
        ),
        migrations.AlterField(
            model_name='permissiondefinition',
            name='id',
            field=models.CharField(help_text='e.g. users.view or PERM-CRM-LEADS-VIEW', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permissiondefinition',
            name='module',
            field=models.CharField(help_text='e.g. CRM, Members, Operations, Finance, Platform, Administration, Users, Roles', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Studio Manager', 'Studio Manager'), ('Operations Manager', 'Operations Manager'), ('Sales', 'Sales'), ('Front Desk', 'Front Desk'), ('Trainer', 'Trainer'), ('Pilates Instructor', 'Pilates Instructor'), ('Nutrition Coach', 'Nutrition Coach'), ('Finance', 'Finance'), ('Support', 'Support'), ('Member', 'Member')], default='Admin', help_text='User role display name in the system', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant organization this user belongs to (null for platform super admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant'),
        ),
    ]
