# Generated by Antigravity - Sprint 5 Schema Field Alignment
import django.db.models.deletion
from django.db import migrations, models


def backfill_sprint5_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    from config.routers import set_tenant_db_alias, get_tenant_db_alias
    old_alias = get_tenant_db_alias()
    set_tenant_db_alias(db_alias)

    try:
        Role = apps.get_model('tenant_core', 'Role')
        TenantUser = apps.get_model('tenant_core', 'TenantUser')
        RoleAssignment = apps.get_model('tenant_core', 'RoleAssignment')
        RolePermissionSet = apps.get_model('tenant_core', 'RolePermissionSet')
        Organization = apps.get_model('tenant_core', 'Organization')
        ModuleCatalog = apps.get_model('tenant_core', 'ModuleCatalog')
        OrganizationSettings = apps.get_model('tenant_core', 'OrganizationSettings')
        NotificationTemplate = apps.get_model('tenant_core', 'NotificationTemplate')
        ConsentRecord = apps.get_model('tenant_core', 'ConsentRecord')
        ProcessingPurpose = apps.get_model('tenant_core', 'ProcessingPurpose')
        TenantAuditEvent = apps.get_model('tenant_core', 'TenantAuditEvent')

        default_org = Organization.objects.using(db_alias).first()

        # 1. Backfill RoleAssignment
        for ra in RoleAssignment.objects.using(db_alias).all():
            updated_fields = []
            if not ra.organization_id:
                org_id = None
                if ra.user_id:
                    user_obj = TenantUser.objects.using(db_alias).filter(id=ra.user_id).first()
                    if user_obj:
                        org_id = user_obj.organization_id
                if not org_id and ra.role_id:
                    role_obj = Role.objects.using(db_alias).filter(id=ra.role_id).first()
                    if role_obj:
                        org_id = role_obj.organization_id
                if not org_id and default_org:
                    org_id = default_org.id
                ra.organization_id = org_id
                updated_fields.append('organization')

            expected_scope = 'BRANCH' if ra.branch_id else 'ORGANIZATION'
            if ra.scope_type != expected_scope:
                ra.scope_type = expected_scope
                updated_fields.append('scope_type')

            expected_status = 'ACTIVE' if ra.is_active else 'INACTIVE'
            if ra.status != expected_status:
                ra.status = expected_status
                updated_fields.append('status')

            if updated_fields:
                ra.save(using=db_alias, update_fields=updated_fields)

        # 2. Backfill RolePermissionSet
        for rps in RolePermissionSet.objects.using(db_alias).all():
            updated_fields = []
            if not rps.organization_id:
                org_id = None
                if rps.role_id:
                    role_obj = Role.objects.using(db_alias).filter(id=rps.role_id).first()
                    if role_obj:
                        org_id = role_obj.organization_id
                if not org_id and default_org:
                    org_id = default_org.id
                rps.organization_id = org_id
                updated_fields.append('organization')

            if not rps.scope_type:
                rps.scope_type = 'ORGANIZATION'
                updated_fields.append('scope_type')

            if rps.is_override is None:
                rps.is_override = False
                updated_fields.append('is_override')

            if updated_fields:
                rps.save(using=db_alias, update_fields=updated_fields)

        # 3. Backfill NotificationTemplate
        for nt in NotificationTemplate.objects.using(db_alias).all():
            updated_fields = []
            if not nt.organization_id and default_org:
                nt.organization_id = default_org.id
                updated_fields.append('organization')
            if not nt.language:
                nt.language = 'en'
                updated_fields.append('language')
            if not nt.version:
                nt.version = 1
                updated_fields.append('version')
            if updated_fields:
                nt.save(using=db_alias, update_fields=updated_fields)

        # 4. Backfill ModuleCatalog source_module_id logically from Master DB
        try:
            from apps.master.models_saas import ProductModule
            for mc in ModuleCatalog.objects.using(db_alias).all():
                pm = ProductModule.objects.using('default').filter(code=mc.module_code).first()
                if pm:
                    mc.source_module_id = pm.id
                    mc.save(using=db_alias, update_fields=['source_module_id'])
        except Exception:
            pass

        # 5. Backfill OrganizationSettings JSONB blocks
        for os_obj in OrganizationSettings.objects.using(db_alias).all():
            updated_fields = []
            for field_name in ['membership_config', 'booking_config', 'attendance_config', 'notification_config', 'ai_config']:
                if getattr(os_obj, field_name) is None:
                    setattr(os_obj, field_name, {})
                    updated_fields.append(field_name)
            if not os_obj.default_timezone:
                os_obj.default_timezone = 'Asia/Kolkata'
                updated_fields.append('default_timezone')
            if not os_obj.language:
                os_obj.language = 'en'
                updated_fields.append('language')
            if not os_obj.date_format:
                os_obj.date_format = 'YYYY-MM-DD'
                updated_fields.append('date_format')
            if not os_obj.time_format:
                os_obj.time_format = 'HH:mm'
                updated_fields.append('time_format')
            if updated_fields:
                os_obj.save(using=db_alias, update_fields=updated_fields)

        # 6. Backfill ConsentRecord & ProcessingPurpose & TenantAuditEvent defaults
        for cr in ConsentRecord.objects.using(db_alias).all():
            updated = []
            if not cr.notice_version:
                cr.notice_version = '1.0'
                updated.append('notice_version')
            if not cr.capture_source:
                cr.capture_source = 'WEB_FORM'
                updated.append('capture_source')
            if cr.proof_metadata is None:
                cr.proof_metadata = {}
                updated.append('proof_metadata')
            if updated:
                cr.save(using=db_alias, update_fields=updated)

        for pp in ProcessingPurpose.objects.using(db_alias).all():
            if not pp.notice_version:
                pp.notice_version = '1.0'
                pp.save(using=db_alias, update_fields=['notice_version'])

        for ae in TenantAuditEvent.objects.using(db_alias).all():
            updated = []
            if not ae.actor_type:
                ae.actor_type = 'TENANT_USER'
                updated.append('actor_type')
            if not ae.source_application:
                ae.source_application = 'web_admin'
                updated.append('source_application')
            if updated:
                ae.save(using=db_alias, update_fields=updated)
    finally:
        set_tenant_db_alias(old_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0001_initial'),
    ]

    operations = [
        # 1. Role: add nullable department FK
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='roles', to='tenant_core.department'
            ),
        ),

        # 2. RoleAssignment: add fields (organization initially nullable for backfill)
        migrations.AddField(
            model_name='roleassignment',
            name='organization',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_assignments', to='tenant_core.organization'
            ),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='scope_type',
            field=models.CharField(
                choices=[
                    ('ORGANIZATION', 'Organization'),
                    ('COMPANY_ENTITY', 'Company Entity'),
                    ('LOCATION', 'Location'),
                    ('BRANCH', 'Branch'),
                ],
                default='ORGANIZATION', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='company_entity',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_assignments', to='tenant_core.companyentity'
            ),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_assignments', to='tenant_core.location'
            ),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='branch',
            field=models.ForeignKey(
                blank=True, help_text='NULL = org-wide scope', null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_assignments', to='tenant_core.branch'
            ),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')],
                default='ACTIVE', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # RoleAssignment.assigned_by: in state remove assigned_by_user_id, add assigned_by FK with db_column='assigned_by_user_id'
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='roleassignment',
                    name='assigned_by_user_id',
                ),
                migrations.AddField(
                    model_name='roleassignment',
                    name='assigned_by',
                    field=models.ForeignKey(
                        blank=True, db_column='assigned_by_user_id', null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_roles', to='tenant_core.tenantuser'
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'role_assignments_assigned_by_user_id_fk'
                        ) THEN
                            ALTER TABLE role_assignments
                            ADD CONSTRAINT role_assignments_assigned_by_user_id_fk
                            FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE SET NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE role_assignments DROP CONSTRAINT IF EXISTS role_assignments_assigned_by_user_id_fk;
                    """
                ),
            ],
        ),

        # 3. RolePermissionSet: add fields (organization initially nullable for backfill)
        migrations.AddField(
            model_name='rolepermissionset',
            name='organization',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_permission_sets', to='tenant_core.organization'
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='scope_type',
            field=models.CharField(
                choices=[
                    ('ORGANIZATION', 'Organization'),
                    ('COMPANY_ENTITY', 'Company Entity'),
                    ('LOCATION', 'Location'),
                    ('BRANCH', 'Branch'),
                ],
                default='ORGANIZATION', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='company_entity',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_permission_sets', to='tenant_core.companyentity'
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='location',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_permission_sets', to='tenant_core.location'
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='branch',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_permission_sets', to='tenant_core.branch'
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='inherits_from',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='child_sets', to='tenant_core.rolepermissionset'
            ),
        ),
        migrations.AddField(
            model_name='rolepermissionset',
            name='is_override',
            field=models.BooleanField(default=False),
        ),

        # 4. ModuleCatalog: source_module_id logical ref
        migrations.AddField(
            model_name='modulecatalog',
            name='source_module_id',
            field=models.UUIDField(
                blank=True, help_text='Logical cross-DB ref to master.ProductModule.id',
                null=True, unique=True
            ),
        ),

        # 5. OrganizationSettings: localization + JSONB blocks
        migrations.AddField(
            model_name='organizationsettings',
            name='default_timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='date_format',
            field=models.CharField(default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='time_format',
            field=models.CharField(default='HH:mm', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='membership_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='booking_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='attendance_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='notification_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='ai_config',
            field=models.JSONField(blank=True, default=dict),
        ),

        # 6. BranchSettings: JSONB override blocks
        migrations.AddField(
            model_name='branchsettings',
            name='membership_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='booking_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='attendance_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='notification_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='ai_config',
            field=models.JSONField(blank=True, null=True),
        ),

        # 7. NotificationTemplate: organization, branch, language, version, event_code
        migrations.AddField(
            model_name='notificationtemplate',
            name='organization',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='notification_templates', to='tenant_core.organization'
            ),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='branch',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                related_name='notification_templates', to='tenant_core.branch'
            ),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),

        # 8. Privacy: ProcessingPurpose & ConsentRecord & TenantAuditEvent
        migrations.AddField(
            model_name='processingpurpose',
            name='notice_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='notice_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='proof_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='capture_source',
            field=models.CharField(default='WEB_FORM', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='actor_type',
            field=models.CharField(
                choices=[
                    ('TENANT_USER', 'Tenant User'),
                    ('SYSTEM_JOB', 'System Job'),
                    ('INTEGRATION', 'Integration'),
                    ('SUPER_ADMIN', 'Super Admin'),
                ],
                default='TENANT_USER', max_length=20
            ),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='company_entity_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='location_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='correlation_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenantauditevent',
            name='source_application',
            field=models.CharField(blank=True, default='web_admin', max_length=100),
        ),

        # 9. Deterministic Data Backfill
        migrations.RunPython(
            backfill_sprint5_data,
            reverse_code=migrations.RunPython.noop,
        ),

        # 10. Enforce non-null constraints after backfill
        migrations.AlterField(
            model_name='roleassignment',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_assignments', to='tenant_core.organization'
            ),
        ),
        migrations.AlterField(
            model_name='rolepermissionset',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='role_permission_sets', to='tenant_core.organization'
            ),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='notification_templates', to='tenant_core.organization'
            ),
        ),

        # 11. Model Meta Options alignment
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['location', 'name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='branchsettings',
            options={'verbose_name_plural': 'Branch settings'},
        ),
        migrations.AlterModelOptions(
            name='companyentity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Company entities'},
        ),
        migrations.AlterModelOptions(
            name='organizationsettings',
            options={'verbose_name_plural': 'Organization settings'},
        ),
        migrations.AlterModelOptions(
            name='userbranch',
            options={'ordering': ['user', 'scope_type'], 'verbose_name_plural': 'User branches'},
        ),
    ]
