# Generated by Django 5.2.3 on 2026-09-11 20:11

import django.db.models.deletion
from django.db import migrations, models


def harden_tenant_fks(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    tenant_fks = [
        ('consent_records', 'user_id', 'users', 'RESTRICT'),
        ('consent_records', 'purpose_id', 'processing_purposes', 'RESTRICT'),
        ('privacy_requests', 'user_id', 'users', 'RESTRICT'),
    ]
    for tbl, col, tgt_tbl, on_delete in tenant_fks:
        cursor.execute(f"""
            SELECT tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
            WHERE tc.table_name = '{tbl}' AND kcu.column_name = '{col}' AND tc.constraint_type = 'FOREIGN KEY';
        """)
        rows = cursor.fetchall()
        for (cname,) in rows:
            cursor.execute(f"ALTER TABLE {tbl} DROP CONSTRAINT {cname};")
            cursor.execute(f"ALTER TABLE {tbl} ADD CONSTRAINT {cname} FOREIGN KEY ({col}) REFERENCES {tgt_tbl}(id) ON DELETE {on_delete};")


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0008_storage_privacy_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_method',
            field=models.CharField(default='WEB_FORM', help_text='e.g. WEB_FORM, PAPER, SMS_OTP, VERBAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='notice_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consents', to='tenant_core.processingpurpose'),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='status',
            field=models.CharField(choices=[('GRANTED', 'Granted'), ('WITHDRAWN', 'Withdrawn'), ('PENDING', 'Pending')], default='GRANTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consents', to='tenant_core.tenantuser'),
        ),
        migrations.AlterField(
            model_name='file',
            name='bucket_name',
            field=models.CharField(default='zata-private-storage', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='classification',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='object_key',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_privacy_requests', to='tenant_core.tenantuser'),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='request_type',
            field=models.CharField(choices=[('ACCESS', 'Right of Access'), ('ERASURE', 'Right to Erasure / Deletion'), ('PORTABILITY', 'Right to Data Portability'), ('RECTIFICATION', 'Right to Rectification'), ('RESTRICTION', 'Right to Restrict Processing'), ('OBJECTION', 'Right to Object')], max_length=40),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('EXTENDED', 'Extended (Timeline Extended)')], default='RECEIVED', max_length=40),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='subject_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='privacyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenant_core.tenantuser'),
        ),
        migrations.AlterField(
            model_name='processingpurpose',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='processingpurpose',
            name='legal_basis',
            field=models.CharField(choices=[('CONSENT', 'Consent'), ('CONTRACT', 'Contract'), ('LEGAL_OBLIGATION', 'Legal Obligation'), ('VITAL_INTERESTS', 'Vital Interests'), ('PUBLIC_TASK', 'Public Task'), ('LEGITIMATE_INTERESTS', 'Legitimate Interests')], default='CONSENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='processingpurpose',
            name='notice_version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='processingpurpose',
            name='retention_days',
            field=models.IntegerField(default=365, help_text='Data retention period in days. -1 = indefinite'),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tenant_core.tenantuser'),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='actor_type',
            field=models.CharField(choices=[('TENANT_USER', 'Tenant User'), ('SYSTEM_JOB', 'System Job'), ('INTEGRATION', 'Integration'), ('SUPER_ADMIN', 'Super Admin')], default='TENANT_USER', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='resource_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tenantauditevent',
            name='source_application',
            field=models.CharField(default='web_admin', max_length=100),
        ),
        migrations.RunPython(
            code=harden_tenant_fks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

