# Generated by Django 5.2.3 on 2026-09-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0017_sprint13_notification_templates_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, db_column='deactivated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_users', to='tenant_core.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='is_login_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('DEACTIVATED', 'Deactivated')], default='INVITED', max_length=30),
        ),
        migrations.RunSQL(
            sql="""
            -- ==========================================================
            -- Sprint 14: users.deactivated_by NOT DEFERRABLE FK hardening
            -- ==========================================================
            DO $$
            DECLARE
                r RECORD;
            BEGIN
                FOR r IN (
                    SELECT conname
                    FROM pg_constraint c
                    JOIN pg_class t ON c.conrelid = t.oid
                    WHERE t.relname = 'users' AND c.contype = 'f'
                      AND EXISTS (
                          SELECT 1 FROM pg_attribute a
                          WHERE a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
                            AND a.attname = 'deactivated_by'
                      )
                ) LOOP
                    EXECUTE 'ALTER TABLE users DROP CONSTRAINT ' || quote_ident(r.conname);
                END LOOP;
            END $$;

            ALTER TABLE users
                ADD CONSTRAINT fk_users_deactivated_by
                FOREIGN KEY (deactivated_by) REFERENCES users(id)
                ON DELETE SET NULL NOT DEFERRABLE;

            ALTER TABLE users ALTER COLUMN is_login_allowed SET DEFAULT TRUE;
            """,
            reverse_sql="""
            ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_deactivated_by;
            """
        ),
    ]
