# Generated by Django 5.1.15 on 2026-09-16 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0019_sprint15_tenant_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('EMPLOYEE', 'Employee'), ('MEMBER', 'Member'), ('SYSTEM', 'System'), ('API', 'API'), ('INTEGRATION', 'Integration')], default='USER', max_length=20)),
                ('actor_employee_profile_id', models.UUIDField(blank=True, help_text='FK to employee_profiles once created', null=True)),
                ('source_channel', models.CharField(choices=[('ADMIN_PANEL', 'Admin Panel'), ('WEB', 'Web'), ('MOBILE_APP', 'Mobile App'), ('FRONT_DESK', 'Front Desk'), ('TRAINER_PANEL', 'Trainer Panel'), ('SALES_PANEL', 'Sales Panel'), ('API', 'API'), ('SYSTEM', 'System'), ('INTEGRATION', 'Integration'), ('MIGRATION', 'Migration')], default='ADMIN_PANEL', max_length=30)),
                ('module', models.CharField(max_length=50)),
                ('action_code', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('parent_entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_entity_id', models.UUIDField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='tenant_core.tenantuser')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_audit_events', to='tenant_core.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_audit_events', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'business_audit_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='biz_audit_org_occurred_idx'), models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='biz_audit_entity_idx'), models.Index(fields=['actor_user', 'occurred_at'], name='biz_audit_actor_idx'), models.Index(fields=['request_id'], name='biz_audit_req_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'domain_outbox_events',
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='outbox_sched_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_agg_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('operation_type', models.CharField(max_length=50)),
                ('request_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('response_snapshot', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.tenantuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_records', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'idempotency_records',
                'indexes': [models.Index(fields=['organization', 'operation_type', 'idempotency_key'], name='idemp_org_op_key_idx'), models.Index(fields=['expires_at'], name='idemp_expires_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'operation_type', 'idempotency_key'), name='uq_idempotency_org_op_key')],
            },
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_comment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reason_codes', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'reason_codes',
                'indexes': [models.Index(fields=['organization', 'module', 'action_type', 'status'], name='reason_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'module', 'action_type', 'code'), name='uq_reason_org_mod_act_code')],
            },
        ),
    ]
