# Generated by Django 5.1.15 on 2026-09-16 09:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0020_businessauditevent_domainoutboxevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('CONSULTANT', 'Consultant'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=30)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('NOTICE_PERIOD', 'Notice Period'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='tenant_core.organization')),
                ('reporting_manager', models.ForeignKey(blank=True, db_column='reporting_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='tenant_core.employeeprofile')),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trainer_code', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trainer_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('can_teach_all_specialties', models.BooleanField(default=False)),
                ('minimum_schedule_buffer_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.OneToOneField(db_column='employee_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='trainer_profile', to='tenant_core.employeeprofile')),
            ],
            options={
                'db_table': 'trainer_profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='trainer_specialties', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'trainer_specialties',
            },
        ),
        migrations.CreateModel(
            name='TrainerSpecialtyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency_level', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('allow_group', models.BooleanField(default=False)),
                ('allow_individual', models.BooleanField(default=False)),
                ('allow_online', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainer_specialty_assignments', to='tenant_core.branch')),
                ('trainer_profile', models.ForeignKey(db_column='trainer_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='specialty_assignments', to='tenant_core.trainerprofile')),
                ('trainer_specialty', models.ForeignKey(db_column='trainer_specialty_id', on_delete=django.db.models.deletion.PROTECT, related_name='trainer_assignments', to='tenant_core.trainerspecialty')),
            ],
            options={
                'db_table': 'trainer_specialty_assignments',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_json', models.JSONField(blank=True, default=dict, null=True)),
                ('emergency_contact_json', models.JSONField(blank=True, default=dict, null=True)),
                ('preferred_language', models.CharField(blank=True, default='en', max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('member_type', models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('TRIAL', 'Trial'), ('GUEST', 'Guest')], default='MEMBER', max_length=30, null=True)),
                ('acquisition_source', models.CharField(blank=True, max_length=30, null=True)),
                ('member_status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, null=True)),
                ('legacy_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_branch', models.ForeignKey(blank=True, db_column='preferred_branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='tenant_core.branch')),
                ('profile_file', models.ForeignKey(blank=True, db_column='profile_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='tenant_core.file')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='tenant_core.tenantuser')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_profile',
            field=models.OneToOneField(db_column='user_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to='tenant_core.userprofile'),
        ),
        migrations.CreateModel(
            name='EmployeeScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_date', models.DateField()),
                ('exception_type', models.CharField(choices=[('LEAVE', 'Leave'), ('WEEKLY_OFF', 'Weekly Off'), ('UNAVAILABLE', 'Unavailable'), ('SPECIAL_SHIFT', 'Special Shift'), ('OTHER', 'Other')], max_length=30)),
                ('is_available', models.BooleanField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='tenant_core.branch')),
                ('employee_profile', models.ForeignKey(db_column='employee_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_exceptions', to='tenant_core.employeeprofile')),
            ],
            options={
                'db_table': 'employee_schedule_exceptions',
                'indexes': [models.Index(fields=['employee_profile', 'exception_date'], name='idx_emp_exc_date'), models.Index(fields=['status'], name='idx_emp_exc_status')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('REGULAR', 'Regular'), ('TEMPORARY', 'Temporary')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_schedules', to='tenant_core.branch')),
                ('employee_profile', models.ForeignKey(db_column='employee_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='tenant_core.employeeprofile')),
            ],
            options={
                'db_table': 'employee_work_schedules',
                'indexes': [models.Index(fields=['employee_profile', 'branch', 'day_of_week'], name='idx_emp_sched_lookup'), models.Index(fields=['status'], name='idx_emp_sched_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='chk_work_sched_day_range')],
            },
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales_code', models.CharField(max_length=100)),
                ('sales_type', models.CharField(choices=[('INSIDE_SALES', 'Inside Sales'), ('FIELD_SALES', 'Field Sales'), ('FRONT_DESK', 'Front Desk'), ('CORPORATE_SALES', 'Corporate Sales'), ('CHANNEL_SALES', 'Channel Sales')], default='INSIDE_SALES', max_length=40)),
                ('target_enabled', models.BooleanField(default=False)),
                ('lead_assignment_enabled', models.BooleanField(default=True)),
                ('sales_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.OneToOneField(db_column='employee_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='sales_profile', to='tenant_core.employeeprofile')),
            ],
            options={
                'db_table': 'sales_profiles',
                'indexes': [models.Index(fields=['sales_status', 'lead_assignment_enabled'], name='idx_sales_active_assign'), models.Index(fields=['sales_code'], name='idx_sales_code')],
            },
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['trainer_status'], name='idx_trainer_status'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['trainer_code'], name='idx_trainer_code'),
        ),
        migrations.AddIndex(
            model_name='trainerspecialty',
            index=models.Index(fields=['organization', 'status'], name='idx_spec_org_status'),
        ),
        migrations.AddConstraint(
            model_name='trainerspecialty',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_spec_org_code'),
        ),
        migrations.AddIndex(
            model_name='trainerspecialtyassignment',
            index=models.Index(fields=['trainer_profile', 'status'], name='idx_tr_spec_assign_status'),
        ),
        migrations.AddIndex(
            model_name='trainerspecialtyassignment',
            index=models.Index(fields=['trainer_specialty', 'status'], name='idx_tr_spec_spec_status'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['member_number'], name='idx_uprof_member_num'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['member_status'], name='idx_uprof_status'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['preferred_branch'], name='idx_uprof_pref_branch'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['organization', 'employment_status'], name='idx_emp_org_status'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_code'], name='idx_emp_code'),
        ),
        migrations.AddConstraint(
            model_name='employeeprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_code'), name='uq_emp_org_code'),
        ),
    ]
