# Generated by Django 5.1.15 on 2026-09-16 09:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0021_employeeprofile_trainerprofile_trainerspecialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('form_type', models.CharField(max_length=100)),
                ('version_number', models.IntegerField(default=1)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='intake_forms', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'intake_forms',
            },
        ),
        migrations.CreateModel(
            name='IntakeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Short Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select'), ('BOOLEAN', 'Yes / No'), ('SCALE', 'Rating Scale')], max_length=30)),
                ('category', models.CharField(choices=[('FITNESS', 'Fitness Background'), ('LIFESTYLE', 'Lifestyle & Nutrition'), ('PSYCHOLOGY', 'Motivation & Mindset'), ('MEDICAL', 'Medical / Health (Protected)'), ('SALES', 'Commercial / Preferences'), ('OTHER', 'Other')], default='FITNESS', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_form', models.ForeignKey(db_column='intake_form_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='tenant_core.intakeform')),
            ],
            options={
                'db_table': 'intake_questions',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='options', to='tenant_core.intakequestion')),
            ],
            options={
                'db_table': 'intake_question_options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intake_form', models.ForeignKey(db_column='intake_form_id', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tenant_core.intakeform')),
                ('submitted_by_user', models.ForeignKey(blank=True, db_column='submitted_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_intakes', to='tenant_core.tenantuser')),
                ('user_profile', models.ForeignKey(blank=True, db_column='user_profile_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_submissions', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'intake_submissions',
            },
        ),
        migrations.CreateModel(
            name='IntakeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='tenant_core.intakequestion')),
                ('submission', models.ForeignKey(db_column='submission_id', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='tenant_core.intakesubmission')),
            ],
            options={
                'db_table': 'intake_answers',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_normalized', models.CharField(blank=True, max_length=32, null=True)),
                ('email_normalized', models.CharField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('current_status', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('TRIAL_BOOKED', 'Trial Booked'), ('TRIAL_CONFIRMED', 'Trial Confirmed'), ('TRIAL_ATTENDED', 'Trial Attended'), ('NO_SHOW', 'No Show'), ('FOLLOW_UP_PENDING', 'Follow-up Pending'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], default='NEW_LEAD', max_length=40)),
                ('first_touch_source', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_touch_source', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sales_user', models.ForeignKey(blank=True, db_column='assigned_sales_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_leads', to='tenant_core.tenantuser')),
                ('assigned_trainer_user', models.ForeignKey(blank=True, db_column='assigned_trainer_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainer_leads', to='tenant_core.tenantuser')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenant_core.branch')),
                ('converted_user_profile', models.ForeignKey(blank=True, db_column='converted_user_profile_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_from_leads', to='tenant_core.userprofile')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='lead',
            field=models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_submissions', to='tenant_core.lead'),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email'), ('VISIT', 'Studio Visit'), ('MEETING', 'Consultation Meeting'), ('FOLLOW_UP', 'Follow-up Call'), ('TRIAL', 'Trial Session'), ('PAYMENT_LINK', 'Payment Link Sent'), ('OTHER', 'Other Interaction')], max_length=30)),
                ('outcome', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='tenant_core.lead')),
                ('performed_by_user', models.ForeignKey(blank=True, db_column='performed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities_performed', to='tenant_core.tenantuser')),
            ],
            options={
                'db_table': 'lead_activities',
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('SALES', 'Sales Representative'), ('TRAINER', 'Coach / Trainer'), ('MANAGER', 'Branch / Studio Manager'), ('OTHER', 'Other')], default='SALES', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, db_column='assigned_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments_given', to='tenant_core.tenantuser')),
                ('assigned_to_user', models.ForeignKey(db_column='assigned_to_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments_received', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tenant_core.lead')),
            ],
            options={
                'db_table': 'lead_assignments',
            },
        ),
        migrations.CreateModel(
            name='LeadConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('converted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_id', models.UUIDField(blank=True, help_text='Logical FK to orders.id', null=True)),
                ('membership_id', models.UUIDField(blank=True, help_text='Logical FK to memberships.id', null=True)),
                ('package_id', models.UUIDField(blank=True, help_text='Logical FK to packages.id', null=True)),
                ('package_version_id', models.UUIDField(blank=True, help_text='Logical FK to package_versions.id', null=True)),
                ('conversion_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted_by_user', models.ForeignKey(blank=True, db_column='converted_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_conversions', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='tenant_core.lead')),
                ('user_profile', models.ForeignKey(db_column='user_profile_id', on_delete=django.db.models.deletion.PROTECT, related_name='lead_conversions', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'lead_conversions',
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('note_type', models.CharField(blank=True, default='GENERAL', max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='lead_notes', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='tenant_core.lead')),
            ],
            options={
                'db_table': 'lead_notes',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('source_type', models.CharField(choices=[('WALK_IN', 'Walk In'), ('WEBSITE', 'Website'), ('MOBILE_APP', 'Mobile App'), ('META', 'Meta / Facebook / Instagram'), ('GOOGLE', 'Google Search / Ads'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone / Direct Call'), ('REFERRAL', 'Member / Friend Referral'), ('TRAINER', 'Trainer Outreach'), ('EMPLOYEE', 'Staff Outreach'), ('SALES', 'Sales Representative'), ('CAMPAIGN', 'Marketing Campaign'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='lead_sources', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'lead_sources',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(blank=True, db_column='lead_source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tenant_core.leadsource'),
        ),
        migrations.CreateModel(
            name='LeadStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=40, null=True)),
                ('to_status', models.CharField(max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by_user', models.ForeignKey(blank=True, db_column='changed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_changes', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='tenant_core.lead')),
            ],
            options={
                'db_table': 'lead_status_history',
            },
        ),
        migrations.CreateModel(
            name='SalesFollowupTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('CALL', 'Phone Call'), ('WHATSAPP', 'WhatsApp Message'), ('EMAIL', 'Email Outreach'), ('MEETING', 'Consultation Meeting'), ('PAYMENT', 'Payment Follow-up'), ('TRIAL_FOLLOWUP', 'Post-Trial Follow-up'), ('REJOIN', 'Rejoin / Winback Outreach'), ('OTHER', 'Other Task')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_user', models.ForeignKey(db_column='assigned_to_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_followup_tasks', to='tenant_core.tenantuser')),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_followup_tasks', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='followup_tasks', to='tenant_core.lead')),
            ],
            options={
                'db_table': 'sales_followup_tasks',
            },
        ),
        migrations.CreateModel(
            name='TrialBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_occurrence_id', models.UUIDField(blank=True, help_text='Logical FK to class_occurrences.id once Module E is active', null=True)),
                ('trial_type', models.CharField(blank=True, default='GROUP_CLASS', max_length=100, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('CONVERTED', 'Converted to Member')], default='BOOKED', max_length=30)),
                ('booking_source', models.CharField(choices=[('WEB', 'Website'), ('MOBILE_APP', 'Mobile App'), ('FRONT_DESK', 'Front Desk'), ('SALES', 'Sales Rep'), ('ADMIN', 'Admin'), ('OTHER', 'Other')], default='WEB', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_trainer_profile', models.ForeignKey(blank=True, db_column='assigned_trainer_profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_bookings', to='tenant_core.trainerprofile')),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.PROTECT, related_name='trial_bookings', to='tenant_core.branch')),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trials', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.PROTECT, related_name='trial_bookings', to='tenant_core.lead')),
                ('user_profile', models.ForeignKey(blank=True, db_column='user_profile_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial_bookings', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'trial_bookings',
            },
        ),
        migrations.CreateModel(
            name='TrialStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(max_length=30)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by_user', models.ForeignKey(blank=True, db_column='changed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_status_changes', to='tenant_core.tenantuser')),
                ('trial_booking', models.ForeignKey(db_column='trial_booking_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='tenant_core.trialbooking')),
            ],
            options={
                'db_table': 'trial_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='intakeform',
            index=models.Index(fields=['organization', 'status'], name='idx_intake_form_status'),
        ),
        migrations.AddConstraint(
            model_name='intakeform',
            constraint=models.UniqueConstraint(fields=('organization', 'form_type', 'version_number'), name='uq_intake_form_ver'),
        ),
        migrations.AddIndex(
            model_name='intakequestion',
            index=models.Index(fields=['intake_form', 'display_order'], name='idx_intake_q_order'),
        ),
        migrations.AddIndex(
            model_name='intakequestion',
            index=models.Index(fields=['is_sensitive'], name='idx_intake_q_sensitive'),
        ),
        migrations.AddConstraint(
            model_name='intakeanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='uq_sub_question_ans'),
        ),
        migrations.AddIndex(
            model_name='intakesubmission',
            index=models.Index(fields=['lead', '-submitted_at'], name='idx_intake_sub_lead'),
        ),
        migrations.AddIndex(
            model_name='intakesubmission',
            index=models.Index(fields=['user_profile', '-submitted_at'], name='idx_intake_sub_uprof'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-activity_at'], name='idx_lead_act_time'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['activity_type'], name='idx_lead_act_type'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['lead', 'status'], name='idx_lead_assign_status'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['assigned_to_user', 'status'], name='idx_lead_assign_user'),
        ),
        migrations.AddIndex(
            model_name='leadconversion',
            index=models.Index(fields=['lead'], name='idx_conv_lead'),
        ),
        migrations.AddIndex(
            model_name='leadconversion',
            index=models.Index(fields=['user_profile'], name='idx_conv_uprof'),
        ),
        migrations.AddIndex(
            model_name='leadconversion',
            index=models.Index(fields=['converted_at'], name='idx_conv_time'),
        ),
        migrations.AddIndex(
            model_name='leadnote',
            index=models.Index(fields=['lead', '-created_at'], name='idx_lead_notes_time'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization', 'status'], name='idx_lead_src_org_status'),
        ),
        migrations.AddConstraint(
            model_name='leadsource',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_lead_source_org_code'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'current_status'], name='idx_lead_org_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['branch', 'current_status'], name='idx_lead_branch_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_normalized'], name='idx_lead_phone'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email_normalized'], name='idx_lead_email'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_sales_user'], name='idx_lead_sales_user'),
        ),
        migrations.AddIndex(
            model_name='leadstatushistory',
            index=models.Index(fields=['lead', 'changed_at'], name='idx_lead_stat_hist_time'),
        ),
        migrations.AddIndex(
            model_name='salesfollowuptask',
            index=models.Index(fields=['assigned_to_user', 'status', 'due_at'], name='idx_sft_user_stat_due'),
        ),
        migrations.AddIndex(
            model_name='salesfollowuptask',
            index=models.Index(fields=['lead', 'status'], name='idx_sft_lead_stat'),
        ),
        migrations.AddIndex(
            model_name='trialbooking',
            index=models.Index(fields=['lead', 'status'], name='idx_trial_lead_status'),
        ),
        migrations.AddIndex(
            model_name='trialbooking',
            index=models.Index(fields=['branch', 'scheduled_start'], name='idx_trial_branch_start'),
        ),
        migrations.AddIndex(
            model_name='trialbooking',
            index=models.Index(fields=['status'], name='idx_trial_status'),
        ),
        migrations.AddIndex(
            model_name='trialstatushistory',
            index=models.Index(fields=['trial_booking', 'changed_at'], name='idx_trial_stat_time'),
        ),
    ]
