# Generated by Django 5.1.15 on 2026-09-16 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0022_intakeform_intakequestion_intakequestionoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=200)),
                ('description_snapshot', models.TextField(blank=True, null=True)),
                ('duration_value', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('DAY', 'Day(s)'), ('WEEK', 'Week(s)'), ('MONTH', 'Month(s)'), ('YEAR', 'Year(s)')], max_length=20)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_trial_package', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FUTURE', 'Future'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_package_versions', to='tenant_core.tenantuser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='tenant_core.package')),
            ],
            options={
                'db_table': 'package_versions',
            },
        ),
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('FUTURE', 'Future'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_prices', to='tenant_core.branch')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_package_prices', to='tenant_core.tenantuser')),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='tenant_core.packageversion')),
            ],
            options={
                'db_table': 'package_prices',
            },
        ),
        migrations.CreateModel(
            name='PackageEntitlementDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entitlement_type', models.CharField(choices=[('HOME_BRANCH_SESSION', 'Home Branch Session'), ('CROSS_BRANCH_SESSION', 'Cross Branch Session'), ('CLASS_SESSION', 'Class Session'), ('PERSONAL_TRAINING_SESSION', 'Personal Training Session'), ('ASSESSMENT', 'Assessment'), ('OPEN_ACCESS', 'Open Access / Gym Floor'), ('OTHER', 'Other')], max_length=50)),
                ('allocated_units', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Scoped entity type e.g. ClassTemplate', max_length=100, null=True)),
                ('reference_id', models.UUIDField(blank=True, help_text='Scoped entity ID', null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_definitions', to='tenant_core.packageversion')),
            ],
            options={
                'db_table': 'package_entitlement_definitions',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(choices=[('MEMBERSHIP', 'Membership'), ('FITNESS', 'Fitness'), ('PERSONAL_TRAINING', 'Personal Training'), ('PILATES', 'Pilates'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other')], default='MEMBERSHIP', max_length=40)),
                ('trial_allowed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tenant_core.program'),
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_categories', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'program_categories',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='tenant_core.programcategory'),
        ),
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(help_text='MEMBERSHIP_TERMS, ATTENDANCE_COMMITMENT_POLICY, CANCELLATION_POLICY, PRIVACY_NOTICE, REWARD_POLICY, etc.', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_documents', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'terms_documents',
            },
        ),
        migrations.CreateModel(
            name='TermsDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content_text', models.TextField(blank=True, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_terms_versions', to='tenant_core.tenantuser')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms_versions', to='tenant_core.file')),
                ('terms_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='tenant_core.termsdocument')),
            ],
            options={
                'db_table': 'terms_document_versions',
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, help_text='Related order ID if accepted at checkout', null=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_via', models.CharField(choices=[('WEB', 'Web'), ('MOBILE_APP', 'Mobile App'), ('FRONT_DESK', 'Front Desk'), ('API', 'API')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms_acceptances', to='tenant_core.lead')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms_acceptances', to='tenant_core.userprofile')),
                ('terms_document_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='tenant_core.termsdocumentversion')),
            ],
            options={
                'db_table': 'terms_acceptances',
            },
        ),
        migrations.CreateModel(
            name='PackageBranchAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=20)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_availabilities', to='tenant_core.branch')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_availabilities', to='tenant_core.package')),
            ],
            options={
                'db_table': 'package_branch_availability',
                'indexes': [models.Index(fields=['branch', 'status'], name='idx_pkgbr_avail_br_status'), models.Index(fields=['package', 'status'], name='idx_pkgbr_avail_pkg_status')],
                'unique_together': {('package', 'branch')},
            },
        ),
        migrations.AddIndex(
            model_name='packageversion',
            index=models.Index(fields=['package', 'status', 'effective_from'], name='idx_pkgver_pkg_st_eff'),
        ),
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together={('package', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='packageprice',
            index=models.Index(fields=['package_version', 'branch', 'status', 'effective_from'], name='idx_pkgprc_ver_br_st_eff'),
        ),
        migrations.AddConstraint(
            model_name='packageprice',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='chk_package_price_base_price_non_neg'),
        ),
        migrations.AddIndex(
            model_name='packageentitlementdefinition',
            index=models.Index(fields=['package_version', 'status'], name='idx_pkgent_ver_status'),
        ),
        migrations.AddIndex(
            model_name='packageentitlementdefinition',
            index=models.Index(fields=['entitlement_type'], name='idx_pkgent_type'),
        ),
        migrations.AddConstraint(
            model_name='packageentitlementdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('is_unlimited', True), ('allocated_units__isnull', False), _connector='OR'), name='chk_pkg_entitlement_units_or_unlimited'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['organization', 'status'], name='idx_pkg_org_status'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['program', 'status'], name='idx_pkg_prog_status'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='programcategory',
            index=models.Index(fields=['organization', 'status', 'display_order'], name='idx_progcat_org_st_ord'),
        ),
        migrations.AlterUniqueTogether(
            name='programcategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organization', 'status'], name='idx_prog_org_status'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['category', 'status'], name='idx_prog_cat_status'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='termsdocument',
            index=models.Index(fields=['organization', 'status'], name='idx_termsdoc_org_status'),
        ),
        migrations.AlterUniqueTogether(
            name='termsdocument',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='termsdocumentversion',
            index=models.Index(fields=['terms_document', 'status', 'effective_from'], name='idx_termsver_doc_st_eff'),
        ),
        migrations.AlterUniqueTogether(
            name='termsdocumentversion',
            unique_together={('terms_document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='termsacceptance',
            index=models.Index(fields=['user_profile', 'accepted_at'], name='idx_termsacc_user_dt'),
        ),
        migrations.AddIndex(
            model_name='termsacceptance',
            index=models.Index(fields=['lead', 'accepted_at'], name='idx_termsacc_lead_dt'),
        ),
        migrations.AddIndex(
            model_name='termsacceptance',
            index=models.Index(fields=['terms_document_version'], name='idx_termsacc_ver'),
        ),
        migrations.AddConstraint(
            model_name='termsacceptance',
            constraint=models.CheckConstraint(condition=models.Q(('lead__isnull', False), ('user_profile__isnull', False), _connector='OR'), name='chk_terms_acceptance_subject'),
        ),
    ]
