# Generated by Django 5.1.15 on 2026-09-16 09:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0023_package_packageversion_packageprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_categories', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'class_categories',
            },
        ),
        migrations.CreateModel(
            name='ClassContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Video Workout / Flow'), ('PDF_GUIDE', 'PDF Workout Card / Guide'), ('AUDIO', 'Audio Playlist / Track'), ('ARTICLE', 'Instruction Article')], default='VIDEO', max_length=30)),
                ('external_url', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_items', to='tenant_core.file')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_content_items', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'class_content_items',
            },
        ),
        migrations.CreateModel(
            name='ClassDemandPlanningRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planning_type', models.CharField(default='WEEKLY', max_length=20)),
                ('analysis_from', models.DateField()),
                ('analysis_to', models.DateField()),
                ('planning_from', models.DateField()),
                ('planning_to', models.DateField()),
                ('status', models.CharField(default='PROPOSED', max_length=30)),
                ('generated_by_type', models.CharField(default='ALGORITHM', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_planning_runs', to='tenant_core.tenantuser')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demand_planning_runs', to='tenant_core.branch')),
                ('generated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_planning_runs', to='tenant_core.tenantuser')),
                ('generated_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_planning_runs', to='tenant_core.file')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_planning_runs', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'class_demand_planning_runs',
            },
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('delivery_mode', models.CharField(default='OFFLINE', max_length=20)),
                ('online_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('online_join_url', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('trial_capacity', models.PositiveIntegerField(default=0)),
                ('waitlist_capacity', models.PositiveIntegerField(default=0)),
                ('booking_open_at', models.DateTimeField(blank=True, null=True)),
                ('booking_close_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('OPEN', 'Open for Booking'), ('FULL', 'Capacity Reached / Full'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_occurrences', to='tenant_core.branch')),
            ],
            options={
                'db_table': 'class_occurrences',
            },
        ),
        migrations.CreateModel(
            name='ClassContentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rotation_cycle_number', models.IntegerField(default=1)),
                ('rotation_position', models.IntegerField(default=1)),
                ('assignment_method', models.CharField(default='ROTATION', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_content_records', to='tenant_core.tenantuser')),
                ('trainer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_content', to='tenant_core.trainerprofile')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_assignments', to='tenant_core.classcontentitem')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_assignments', to='tenant_core.classoccurrence')),
            ],
            options={
                'db_table': 'class_content_assignments',
            },
        ),
        migrations.CreateModel(
            name='ClassOccurrenceTrainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trainer_role', models.CharField(choices=[('LEAD', 'Lead Trainer'), ('ASSISTANT', 'Assistant Trainer'), ('SUBSTITUTE', 'Substitute Trainer')], default='LEAD', max_length=20)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REPLACED', 'Replaced')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_trainers', to='tenant_core.tenantuser')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_assignments', to='tenant_core.classoccurrence')),
                ('trainer_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_assignments', to='tenant_core.trainerprofile')),
            ],
            options={
                'db_table': 'class_occurrence_trainers',
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_source', models.CharField(default='CSV', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_import_batches', to='tenant_core.branch')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_import_batches', to='tenant_core.file')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_import_batches', to='tenant_core.organization')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_class_imports', to='tenant_core.tenantuser')),
            ],
            options={
                'db_table': 'class_schedule_import_batches',
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(default='WEEKLY', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='[1, 2, ..., 7] for Mon-Sun', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('delivery_mode', models.CharField(default='OFFLINE', max_length=20)),
                ('recurrence_config', models.JSONField(blank=True, default=dict, null=True)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist_capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedule_rules', to='tenant_core.branch')),
            ],
            options={
                'db_table': 'class_schedule_rules',
            },
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='schedule_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_occurrences', to='tenant_core.classschedulerule'),
        ),
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('default_capacity', models.PositiveIntegerField(default=20)),
                ('default_trial_capacity', models.PositiveIntegerField(default=0)),
                ('default_waitlist_capacity', models.PositiveIntegerField(default=0)),
                ('default_delivery_mode', models.CharField(choices=[('OFFLINE', 'Offline / Studio'), ('ONLINE', 'Online Live Stream'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('allow_booking', models.BooleanField(default=True)),
                ('allow_trial', models.BooleanField(default=False)),
                ('allow_waitlist', models.BooleanField(default=False)),
                ('allow_reschedule', models.BooleanField(default=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_templates', to='tenant_core.classcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_templates', to='tenant_core.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_templates', to='tenant_core.program')),
            ],
            options={
                'db_table': 'class_templates',
            },
        ),
        migrations.CreateModel(
            name='ClassSpecialtyRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_proficiency_level', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_requirements', to='tenant_core.trainerspecialty')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_requirements', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_specialty_requirements',
            },
        ),
        migrations.AddField(
            model_name='classschedulerule',
            name='class_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_rules', to='tenant_core.classtemplate'),
        ),
        migrations.CreateModel(
            name='ClassScheduleRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('recommended_date', models.DateField(blank=True, null=True)),
                ('recommended_start_time', models.TimeField()),
                ('recommended_end_time', models.TimeField()),
                ('recommended_delivery_mode', models.CharField(default='OFFLINE', max_length=20)),
                ('recommended_capacity', models.IntegerField(default=20)),
                ('recommended_occurrence_count', models.IntegerField(default=1)),
                ('demand_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('recommendation_type', models.CharField(default='ADD_OCCURRENCE', max_length=30)),
                ('reason_codes', models.JSONField(blank=True, default=list, null=True)),
                ('historical_metrics', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(default='PROPOSED', max_length=20)),
                ('manager_comment', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_recommendations', to='tenant_core.branch')),
                ('planning_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='tenant_core.classdemandplanningrun')),
                ('recommended_content_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.classcontentitem')),
                ('recommended_trainer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.trainerprofile')),
                ('recommended_trainer_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.trainerspecialty')),
                ('reviewed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to='tenant_core.tenantuser')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_recommendations', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_schedule_recommendations',
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('class_name_input', models.CharField(max_length=250)),
                ('trainer_name_input', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('delivery_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('validation_status', models.CharField(default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.branch')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tenant_core.classscheduleimportbatch')),
                ('trainer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.trainerprofile')),
                ('created_schedule_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.classschedulerule')),
                ('class_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_schedule_import_rows',
            },
        ),
        migrations.CreateModel(
            name='ClassPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_prices', to='tenant_core.branch')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_class_prices', to='tenant_core.tenantuser')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_prices',
            },
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='class_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='tenant_core.classtemplate'),
        ),
        migrations.CreateModel(
            name='ClassDemandEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(help_text='BOOKING_CREATED, WAITLIST_JOINED, ATTENDED, NO_SHOW, CANCELLED_LATE, CANCELLED_EARLY', max_length=40)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_demand_events', to='tenant_core.branch')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_demand_events', to='tenant_core.userprofile')),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_events', to='tenant_core.classoccurrence')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_events', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_demand_events',
            },
        ),
        migrations.CreateModel(
            name='ClassContentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_mappings', to='tenant_core.branch')),
                ('class_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_mappings', to='tenant_core.classcategory')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='tenant_core.classcontentitem')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_mappings', to='tenant_core.program')),
                ('trainer_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_mappings', to='tenant_core.trainerspecialty')),
                ('class_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_mappings', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_content_mappings',
            },
        ),
        migrations.CreateModel(
            name='ClassBranchAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ENABLED', max_length=20)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('waitlist_capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_availabilities', to='tenant_core.branch')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_availabilities', to='tenant_core.classtemplate')),
            ],
            options={
                'db_table': 'class_branch_availability',
            },
        ),
        migrations.CreateModel(
            name='PackageClassAccessRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('INCLUDED', 'Included in Package'), ('EXCLUDED', 'Explicitly Excluded'), ('DISCOUNTED', 'Discounted Rate')], default='INCLUDED', max_length=20)),
                ('entitlement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('units_per_booking', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_class_rules', to='tenant_core.branch')),
                ('class_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_access_rules', to='tenant_core.classcategory')),
                ('class_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_access_rules', to='tenant_core.classtemplate')),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_access_rules', to='tenant_core.packageversion')),
            ],
            options={
                'db_table': 'package_class_access_rules',
            },
        ),
        migrations.AddIndex(
            model_name='classcategory',
            index=models.Index(fields=['organization', 'status', 'display_order'], name='idx_clscat_org_st_ord'),
        ),
        migrations.AlterUniqueTogether(
            name='classcategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='classcontentitem',
            index=models.Index(fields=['organization', 'status', 'display_order'], name='idx_clsitm_org_st_ord'),
        ),
        migrations.AddConstraint(
            model_name='classcontentitem',
            constraint=models.CheckConstraint(condition=models.Q(('external_url__isnull', False), ('file__isnull', False), _connector='OR'), name='chk_content_item_has_source'),
        ),
        migrations.AddIndex(
            model_name='classdemandplanningrun',
            index=models.Index(fields=['organization', 'status', 'planning_from'], name='idx_dmdrun_org_st_pf'),
        ),
        migrations.AddIndex(
            model_name='classdemandplanningrun',
            index=models.Index(fields=['branch', 'planning_from'], name='idx_dmdrun_br_pf'),
        ),
        migrations.AddIndex(
            model_name='classcontentassignment',
            index=models.Index(fields=['occurrence', 'status'], name='idx_clsass_occ_status'),
        ),
        migrations.AddIndex(
            model_name='classcontentassignment',
            index=models.Index(fields=['content_item', 'rotation_cycle_number'], name='idx_clsass_item_cycle'),
        ),
        migrations.AddIndex(
            model_name='classcontentassignment',
            index=models.Index(fields=['trainer_profile', 'assigned_at'], name='idx_clsass_trn_dt'),
        ),
        migrations.AddIndex(
            model_name='classoccurrencetrainer',
            index=models.Index(fields=['occurrence', 'status'], name='idx_clstrn_occ_status'),
        ),
        migrations.AddIndex(
            model_name='classoccurrencetrainer',
            index=models.Index(fields=['trainer_profile', 'status'], name='idx_clstrn_prof_status'),
        ),
        migrations.AddIndex(
            model_name='classscheduleimportbatch',
            index=models.Index(fields=['organization', 'status', 'uploaded_at'], name='idx_clsimp_org_st_up'),
        ),
        migrations.AddIndex(
            model_name='classscheduleimportbatch',
            index=models.Index(fields=['branch', 'uploaded_at'], name='idx_clsimp_br_up'),
        ),
        migrations.AddIndex(
            model_name='classtemplate',
            index=models.Index(fields=['organization', 'status'], name='idx_clstpl_org_status'),
        ),
        migrations.AddIndex(
            model_name='classtemplate',
            index=models.Index(fields=['program', 'status'], name='idx_clstpl_prog_status'),
        ),
        migrations.AddIndex(
            model_name='classtemplate',
            index=models.Index(fields=['category', 'status'], name='idx_clstpl_cat_status'),
        ),
        migrations.AlterUniqueTogether(
            name='classtemplate',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='classspecialtyrequirement',
            index=models.Index(fields=['class_template', 'status'], name='idx_clsspec_tpl_status'),
        ),
        migrations.AddIndex(
            model_name='classspecialtyrequirement',
            index=models.Index(fields=['trainer_specialty', 'status'], name='idx_clsspec_spec_status'),
        ),
        migrations.AlterUniqueTogether(
            name='classspecialtyrequirement',
            unique_together={('class_template', 'trainer_specialty')},
        ),
        migrations.AddIndex(
            model_name='classschedulerule',
            index=models.Index(fields=['branch', 'status', 'valid_from'], name='idx_clssch_br_st_vf'),
        ),
        migrations.AddIndex(
            model_name='classschedulerule',
            index=models.Index(fields=['class_template', 'status'], name='idx_clssch_tpl_status'),
        ),
        migrations.AddConstraint(
            model_name='classschedulerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_schedule_rule_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='classschedulerecommendation',
            index=models.Index(fields=['planning_run', 'status'], name='idx_dmdrec_run_status'),
        ),
        migrations.AddIndex(
            model_name='classschedulerecommendation',
            index=models.Index(fields=['branch', 'class_template', 'recommended_date'], name='idx_dmdrec_br_tpl_dt'),
        ),
        migrations.AddIndex(
            model_name='classscheduleimportrow',
            index=models.Index(fields=['import_batch', 'validation_status'], name='idx_clsrow_batch_status'),
        ),
        migrations.AlterUniqueTogether(
            name='classscheduleimportrow',
            unique_together={('import_batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='classprice',
            index=models.Index(fields=['class_template', 'branch', 'status', 'effective_from'], name='idx_clsprc_tpl_br_st_eff'),
        ),
        migrations.AddConstraint(
            model_name='classprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='chk_class_price_non_neg'),
        ),
        migrations.AlterUniqueTogether(
            name='classprice',
            unique_together={('class_template', 'branch', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['branch', 'start_at', 'status'], name='idx_clsocc_br_st_status'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['class_template', 'start_at'], name='idx_clsocc_tpl_start'),
        ),
        migrations.AddIndex(
            model_name='classoccurrence',
            index=models.Index(fields=['schedule_rule'], name='idx_clsocc_rule'),
        ),
        migrations.AddConstraint(
            model_name='classoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_occurrence_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='classdemandevent',
            index=models.Index(fields=['branch', 'class_template', 'event_at'], name='idx_dmd_br_tpl_dt'),
        ),
        migrations.AddIndex(
            model_name='classdemandevent',
            index=models.Index(fields=['occurrence', 'event_at'], name='idx_dmd_occ_dt'),
        ),
        migrations.AddIndex(
            model_name='classdemandevent',
            index=models.Index(fields=['event_type', 'event_at'], name='idx_dmd_type_dt'),
        ),
        migrations.AddIndex(
            model_name='classcontentmapping',
            index=models.Index(fields=['content_item', 'status'], name='idx_clsmap_item_status'),
        ),
        migrations.AddIndex(
            model_name='classcontentmapping',
            index=models.Index(fields=['class_template', 'status'], name='idx_clsmap_tpl_status'),
        ),
        migrations.AddIndex(
            model_name='classcontentmapping',
            index=models.Index(fields=['program', 'status'], name='idx_clsmap_prog_status'),
        ),
        migrations.AddIndex(
            model_name='classcontentmapping',
            index=models.Index(fields=['trainer_specialty', 'status'], name='idx_clsmap_spec_status'),
        ),
        migrations.AddIndex(
            model_name='classbranchavailability',
            index=models.Index(fields=['branch', 'status'], name='idx_clsbr_avail_br_status'),
        ),
        migrations.AddIndex(
            model_name='classbranchavailability',
            index=models.Index(fields=['class_template', 'status'], name='idx_clsbr_avail_tpl_status'),
        ),
        migrations.AlterUniqueTogether(
            name='classbranchavailability',
            unique_together={('class_template', 'branch')},
        ),
        migrations.AddIndex(
            model_name='packageclassaccessrule',
            index=models.Index(fields=['package_version', 'status'], name='idx_pkgcls_ver_status'),
        ),
        migrations.AddIndex(
            model_name='packageclassaccessrule',
            index=models.Index(fields=['class_template'], name='idx_pkgcls_tpl'),
        ),
        migrations.AddIndex(
            model_name='packageclassaccessrule',
            index=models.Index(fields=['class_category'], name='idx_pkgcls_cat'),
        ),
        migrations.AddConstraint(
            model_name='packageclassaccessrule',
            constraint=models.CheckConstraint(condition=models.Q(('class_template__isnull', False), ('class_category__isnull', False), _connector='OR'), name='chk_pkg_class_rule_target'),
        ),
    ]
