# Generated by Django 5.1.15 on 2026-09-16 10:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0024_classcategory_classcontentitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('default_delivery_mode', models.CharField(choices=[('OFFLINE', 'Offline / Studio'), ('ONLINE', 'Online Live Stream'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('requires_trainer', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_types', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'appointment_types',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_id', models.UUIDField(blank=True, null=True)),
                ('entitlement_id', models.UUIDField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('delivery_mode', models.CharField(choices=[('OFFLINE', 'Offline / Studio'), ('ONLINE', 'Online Live Stream'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20)),
                ('online_join_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=30)),
                ('booking_source', models.CharField(choices=[('WEB', 'Web Portal'), ('MOBILE_APP', 'Mobile App'), ('FRONT_DESK', 'Front Desk'), ('ADMIN', 'Admin Console'), ('API', 'External API'), ('OTHER', 'Other')], default='ADMIN', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenant_core.branch')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='tenant_core.tenantuser')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenant_core.userprofile')),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenant_core.appointmenttype')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='AppointmentTypeSpecialtyRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimum_proficiency_level', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BASIC', max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_requirements', to='tenant_core.appointmenttype')),
                ('trainer_specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_type_requirements', to='tenant_core.trainerspecialty')),
            ],
            options={
                'db_table': 'appointment_type_specialty_requirements',
            },
        ),
        migrations.CreateModel(
            name='AppointmentTrainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEAD', 'Lead Trainer'), ('ASSISTANT', 'Assistant Trainer'), ('SUBSTITUTE', 'Substitute Trainer')], default='LEAD', max_length=20)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REPLACED', 'Replaced')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trainers', to='tenant_core.appointment')),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointment_trainers', to='tenant_core.tenantuser')),
                ('trainer_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_assignments', to='tenant_core.trainerprofile')),
            ],
            options={
                'db_table': 'appointment_trainers',
                'indexes': [models.Index(fields=['appointment', 'status'], name='idx_appttrain_appt_status'), models.Index(fields=['trainer_profile', 'status'], name='idx_appttrain_prof_status')],
                'unique_together': {('appointment', 'trainer_profile')},
            },
        ),
        migrations.AddIndex(
            model_name='appointmenttype',
            index=models.Index(fields=['organization', 'status'], name='idx_appttype_org_status'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttype',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'start_at', 'status'], name='idx_appt_br_st_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user_profile', 'start_at'], name='idx_appt_uprof_start'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='chk_appointment_end_gt_start'),
        ),
        migrations.AddIndex(
            model_name='appointmenttypespecialtyrequirement',
            index=models.Index(fields=['appointment_type', 'status'], name='idx_apptspec_type_st'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttypespecialtyrequirement',
            unique_together={('appointment_type', 'trainer_specialty')},
        ),
    ]
