# Generated by Django 5.1.15 on 2026-09-16 10:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0025_appointmenttype_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('NEW_MEMBERSHIP', 'New Membership'), ('RENEWAL', 'Membership Renewal'), ('EXTENSION', 'Membership Extension'), ('UPGRADE', 'Membership Upgrade'), ('DOWNGRADE', 'Membership Downgrade'), ('REJOIN', 'Rejoin Membership'), ('CLASS_PURCHASE', 'Class Session Purchase'), ('APPOINTMENT_PURCHASE', 'Appointment Service Purchase'), ('OTHER', 'Other Commercial Purchase')], default='NEW_MEMBERSHIP', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid / Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('source', models.CharField(choices=[('WEB', 'Web Checkout'), ('MOBILE_APP', 'Mobile App'), ('FRONT_DESK', 'Front Desk POS'), ('SALES', 'Sales Representative'), ('POS', 'Point of Sale Machine'), ('API', 'External API'), ('MIGRATION', 'Data Migration')], default='FRONT_DESK', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenant_core.branch')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenant_core.lead')),
                ('sold_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_orders', to='tenant_core.tenantuser')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='MemberInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenant_core.branch')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenant_core.file')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenant_core.userprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenant_core.order')),
            ],
            options={
                'db_table': 'member_invoices',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PACKAGE', 'Package Version'), ('CLASS', 'Group Class'), ('APPOINTMENT', 'Appointment Service'), ('OTHER', 'Other Product / Service')], default='PACKAGE', max_length=20)),
                ('item_name_snapshot', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_percent_snapshot', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.appointmenttype')),
                ('class_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.classprice')),
                ('class_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.classtemplate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='tenant_core.order')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.package')),
                ('package_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.packageprice')),
                ('package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenant_core.packageversion')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='RAZORPAY', max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_links', to='tenant_core.tenantuser')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='tenant_core.lead')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='tenant_core.order')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'payment_links',
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('OPENED', 'Opened'), ('PAYMENT_ATTEMPTED', 'Payment Attempted'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tenant_core.paymentlink')),
            ],
            options={
                'db_table': 'payment_link_events',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('ICICI_POS', 'ICICI POS'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / RTGS'), ('STRIPE', 'Stripe'), ('OTHER', 'Other Provider')], default='CASH', max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenant_core.order')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to='tenant_core.tenantuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenant_core.order')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenant_core.paymenttransaction')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to='tenant_core.tenantuser')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='idx_orders_order_num'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_profile', 'status', 'created_at'], name='idx_orders_uprof_st_dt'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['lead', 'status'], name='idx_orders_lead_st'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_at'], name='idx_orders_br_dt'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0.00'))), name='chk_order_total_non_neg'),
        ),
        migrations.AddIndex(
            model_name='memberinvoice',
            index=models.Index(fields=['invoice_number'], name='idx_inv_num'),
        ),
        migrations.AddIndex(
            model_name='memberinvoice',
            index=models.Index(fields=['order'], name='idx_inv_order'),
        ),
        migrations.AddIndex(
            model_name='memberinvoice',
            index=models.Index(fields=['user_profile', 'issued_at'], name='idx_inv_uprof_dt'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orditem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['package_version'], name='idx_orditem_pkgver'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['class_template'], name='idx_orditem_clstpl'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['order', 'status'], name='idx_paylink_ord_status'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['external_reference'], name='idx_paylink_ext_ref'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['expires_at', 'status'], name='idx_paylink_exp_status'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkevent',
            index=models.Index(fields=['payment_link', 'event_at'], name='idx_plevt_link_dt'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkevent',
            index=models.Index(fields=['provider_reference'], name='idx_plevt_prov_ref'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='idx_paytxn_ord_status'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='idx_paytxn_prov_id'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['idempotency_key'], name='idx_paytxn_idem_key'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment_transaction', 'status'], name='idx_ref_pay_status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'status'], name='idx_ref_ord_status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['provider_reference'], name='idx_ref_prov_ref'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='chk_refund_amount_positive'),
        ),
    ]
