# Generated by Django 5.1.15 on 2026-09-16 10:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0026_order_memberinvoice_orderitem_paymentlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('per_user_limit', models.IntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_campaigns', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'discount_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_codes', to='tenant_core.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='tenant_core.discountcampaign')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_codes', to='tenant_core.package')),
            ],
            options={
                'db_table': 'discount_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DiscountEligibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('COUPON', 'Coupon Eligibility Rule'), ('AUTO_DISCOUNT', 'Automatic Discount Rule'), ('OFFER', 'Dynamic Promotional Offer'), ('UPGRADE_OFFER', 'Upgrade Incentive Offer'), ('CROSS_SELL', 'Cross-Sell Offer'), ('RENEWAL', 'Renewal Incentive Offer'), ('REJOIN', 'Rejoin Incentive Offer')], default='COUPON', max_length=30)),
                ('priority', models.IntegerField(default=100)),
                ('evaluation_mode', models.CharField(choices=[('ALL_CONDITIONS', 'All Conditions Must Match (AND)'), ('ANY_CONDITION', 'Any Condition Matches (OR)')], default='ALL_CONDITIONS', max_length=20)),
                ('rule_behavior', models.CharField(default='TRANSACTIONAL', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_eligibility_rules', to='tenant_core.branch')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_discount_rules', to='tenant_core.tenantuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_eligibility_rules', to='tenant_core.organization')),
                ('source_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_eligibility_rules', to='tenant_core.package')),
                ('source_package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_version_eligibility_rules', to='tenant_core.packageversion')),
                ('target_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_eligibility_rules', to='tenant_core.package')),
                ('target_package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_version_eligibility_rules', to='tenant_core.packageversion')),
            ],
            options={
                'db_table': 'discount_eligibility_rules',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='tenant_core.discountcampaign')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='tenant_core.discountcode')),
                ('eligibility_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='tenant_core.discounteligibilityrule')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_redemptions', to='tenant_core.order')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_redemptions', to='tenant_core.userprofile')),
            ],
            options={
                'db_table': 'discount_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRuleAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SHOW_COUPON', 'Show Coupon Code'), ('APPLY_COUPON', 'Apply Coupon Code'), ('APPLY_PERCENTAGE_DISCOUNT', 'Apply Percentage Discount'), ('APPLY_FIXED_DISCOUNT', 'Apply Fixed Discount'), ('SHOW_OFFER', 'Show Dynamic Offer Banner'), ('ALLOW_UPGRADE_PRICE', 'Allow Special Upgrade Price'), ('GENERATE_COUPON', 'Generate Unique Coupon')], max_length=40)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('auto_apply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_actions', to='tenant_core.discountcampaign')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_actions', to='tenant_core.discountcode')),
                ('discount_eligibility_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='tenant_core.discounteligibilityrule')),
            ],
            options={
                'db_table': 'discount_rule_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRuleCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(max_length=60)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals (==)'), ('NOT_EQUALS', 'Not Equals (!=)'), ('GREATER_THAN', 'Greater Than (>)'), ('GREATER_THAN_OR_EQUAL', 'Greater Than or Equal (>=)'), ('LESS_THAN', 'Less Than (<)'), ('LESS_THAN_OR_EQUAL', 'Less Than or Equal (<=)'), ('IN', 'In List'), ('NOT_IN', 'Not In List'), ('BETWEEN', 'Between Range'), ('EXISTS', 'Exists / True'), ('NOT_EXISTS', 'Not Exists / False')], max_length=30)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_eligibility_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='tenant_core.discounteligibilityrule')),
            ],
            options={
                'db_table': 'discount_rule_conditions',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code', 'status'], name='discount_co_code_9b4565_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountcode',
            unique_together={('campaign', 'code')},
        ),
    ]
