# Generated by Django 5.2.3 on 2026-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0029_approvalrequest_approvalaction_attendancepolicyset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
