# Generated by Django 5.1.15 on 2026-09-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0031_program_package_session_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='legacy_program_type',
            field=models.CharField(db_column='program_type', default='MEMBERSHIP', max_length=40),
        ),
    ]
