# Generated by Django 5.2.17 on 2026-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0032_alter_program_legacy_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchworkinghours',
            name='close_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchworkinghours',
            name='has_split_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchworkinghours',
            name='open_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
