# Generated by Django 5.2.3 on 2026-09-19 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0032_alter_program_legacy_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_program',
            field=models.ForeignKey(blank=True, db_column='interested_program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='tenant_core.program'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by_user',
            field=models.ForeignKey(blank=True, db_column='referred_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to='tenant_core.tenantuser'),
        ),
        migrations.CreateModel(
            name='LeadCommercialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='tenant_core.lead')),
            ],
            options={
                'db_table': 'lead_commercial_profiles',
            },
        ),
    ]
