# Generated by Django 5.2.3 on 2026-09-21 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0033_lead_legacy_fields_and_commercial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMTrialReminderPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('immediate_whatsapp', models.BooleanField(default=True)),
                ('immediate_email', models.BooleanField(default=True)),
                ('immediate_sms', models.BooleanField(default=False)),
                ('reminder_offsets', models.JSONField(blank=True, default=list)),
                ('ask_attendance_confirmation', models.BooleanField(default=True)),
                ('confirmation_wait_duration_value', models.PositiveIntegerField(default=2)),
                ('confirmation_wait_duration_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days')], default='HOURS', max_length=20)),
                ('no_response_action', models.CharField(choices=[('CREATE_FOLLOWUP', 'Create Follow-up Task'), ('NOTIFY_AGENT', 'Notify Assigned Agent'), ('NONE', 'No Action')], default='CREATE_FOLLOWUP', max_length=30)),
                ('ai_calling_enabled', models.BooleanField(default=False, help_text='AI calling integration status (unavailable in current phase)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='crm_trial_reminder_policy', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_trial_reminder_policies',
            },
        ),
        migrations.CreateModel(
            name='CRMStageSlaPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_stage', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('TRIAL_BOOKED', 'Trial Booked'), ('TRIAL_CONFIRMED', 'Trial Confirmed'), ('TRIAL_ATTENDED', 'Trial Attended'), ('NO_SHOW', 'No Show'), ('FOLLOW_UP_PENDING', 'Follow-up Pending'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], max_length=50)),
                ('display_label', models.CharField(max_length=150)),
                ('response_target_value', models.PositiveIntegerField(default=15)),
                ('response_target_unit', models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='MINUTES', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('escalation_enabled', models.BooleanField(default=False)),
                ('escalation_after_value', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_after_unit', models.CharField(blank=True, choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='HOURS', max_length=20, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='crm_stage_sla_policies', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_stage_sla_policies',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'canonical_stage'), name='uq_crm_sla_org_stage')],
            },
        ),
    ]
