# Generated by Django 5.2.17 on 2026-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0033_branchworkinghours_close_time_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeescheduleexception',
            name='exception_type',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('WEEKLY_OFF', 'Weekly Off'), ('WEEKLY_OFF_OVERRIDE', 'Weekly Off Override'), ('SPECIAL_SHIFT', 'Special Shift'), ('UNAVAILABLE', 'Unavailable'), ('TEMPORARY_AVAILABILITY', 'Temporary Availability'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
