# Generated by Django 5.2.3 on 2026-09-21 09:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0034_crmtrialreminderpolicy_crmstageslapolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('touch_type', models.CharField(choices=[('FIRST_TOUCH', 'First Touch (Initial Discovery)'), ('LEAD_CAPTURE', 'Lead Capture (Form / Conversion Submission)'), ('ASSISTED_TOUCH', 'Assisted Touch (Follow-up / Secondary Channel)')], default='LEAD_CAPTURE', max_length=30)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ad_set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_set_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('form_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('external_lead_id', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=150, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=150, null=True)),
                ('landing_page_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('referrer_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('capture_method', models.CharField(blank=True, default='MANUAL', max_length=50, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='tenant_core.lead')),
                ('lead_source', models.ForeignKey(blank=True, db_column='lead_source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='tenant_core.leadsource')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='lead_attributions', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_lead_attributions',
                'ordering': ['captured_at', 'created_at'],
                'indexes': [models.Index(fields=['lead', 'touch_type'], name='idx_attr_lead_touch'), models.Index(fields=['organization', 'platform'], name='idx_attr_org_platform'), models.Index(fields=['campaign_name'], name='idx_attr_campaign'), models.Index(fields=['external_lead_id'], name='idx_attr_ext_lead'), models.Index(fields=['utm_source', 'utm_medium'], name='idx_attr_utm')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_lead_id__isnull', False), models.Q(('external_lead_id', ''), _negated=True)), fields=('organization', 'platform', 'external_lead_id'), name='uq_org_platform_ext_lead_id')],
            },
        ),
    ]
