# Generated by Django 5.2.17 on 2026-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0034_alter_employeescheduleexception_exception_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='geofence_distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_within_geofence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='liveness_challenges_passed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='liveness_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='liveness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='trainer_accuracy_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='trainer_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='trainer_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='trainer_selfie_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_enforcement',
            field=models.CharField(choices=[('STRICT', 'Strict Lock'), ('FLAG_AUDIT', 'Audit Flag Only')], default='STRICT', help_text='Strictly block attendance or flag for audit when outside radius', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='geofence_radius_meters',
            field=models.IntegerField(default=200, help_text='Maximum allowed distance in meters for attendance check-in'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_method',
            field=models.CharField(choices=[('BARCODE', 'BARCODE'), ('QR', 'QR'), ('ACCESS_DEVICE', 'ACCESS_DEVICE'), ('MOBILE', 'MOBILE'), ('FRONT_DESK', 'FRONT_DESK'), ('ADMIN', 'ADMIN'), ('FACE_LIVENESS', 'FACE_LIVENESS')], default='QR', max_length=30),
        ),
    ]
