# Generated by Django 5.2.3 on 2026-09-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0035_leadattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='no_show_followup_delay_unit',
            field=models.CharField(default='MINUTES', max_length=20),
        ),
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='no_show_followup_delay_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='no_show_followup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='post_attended_followup_delay_unit',
            field=models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days')], default='HOURS', max_length=20),
        ),
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='post_attended_followup_delay_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmtrialreminderpolicy',
            name='post_attended_followup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='confirmation_channel',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('PHONE', 'Phone Call'), ('IN_PERSON', 'In Person'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('API', 'API')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='confirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialbooking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, db_column='rescheduled_from_trial_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_trials', to='tenant_core.trialbooking'),
        ),
        migrations.AddField(
            model_name='salesfollowuptask',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
