# Generated by Django 5.2.3 on 2026-09-21 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0036_trialbooking_confirmation_and_post_trial_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_status', models.CharField(choices=[('RESOLVED', 'Resolved to a single Lead'), ('UNRESOLVED', 'Unknown sender phone/email (Lead is null)'), ('AMBIGUOUS', 'Multiple matching Leads found (Lead is null)')], default='RESOLVED', max_length=20)),
                ('sender_identifier', models.CharField(blank=True, default='', help_text='Sender phone number or email address', max_length=255)),
                ('raw_sender_data', models.JSONField(blank=True, default=dict, help_text='Safe sender payload metadata for unresolved or ambiguous inbound messages')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('VOICE', 'Voice Call'), ('AI_CALL', 'AI Call'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Message')], max_length=30)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound (System / Agent to Customer)'), ('INBOUND', 'Inbound (Customer to System)')], default='OUTBOUND', max_length=20)),
                ('purpose', models.CharField(choices=[('TRANSACTIONAL', 'Transactional / Service Alert'), ('MARKETING', 'Marketing / Promotional')], default='TRANSACTIONAL', max_length=30)),
                ('recipient', models.CharField(help_text='Destination phone or email', max_length=255)),
                ('sender', models.CharField(blank=True, default='', help_text='Sender ID or from address', max_length=255)),
                ('template_reference', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', help_text='Email subject line', max_length=300)),
                ('body_snapshot', models.TextField(help_text='Immutable rendered snapshot of sent/received content')),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. Meta, Gupshup, SMTP, SES, Twilio', max_length=100)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued for Dispatch'), ('SUBMITTED', 'Submitted to Provider'), ('SENT', 'Sent by Provider'), ('DELIVERED', 'Delivered to Recipient Device'), ('READ', 'Read by Recipient'), ('RECEIVED', 'Received Inbound Message'), ('REPLIED', 'Customer Replied'), ('FAILED', 'Delivery Failed'), ('CANCELLED', 'Dispatch Cancelled')], default='QUEUED', max_length=30)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(blank=True, default='MANUAL', help_text='e.g. MANUAL, TRIAL_CONFIRMATION, TRIAL_REMINDER, LEAD_WELCOME, FOLLOWUP_TASK', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communication_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Sanitized, safely redacted provider webhook metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_status_events',
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='salesfollowuptask',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference__isnull', False)), fields=('lead', 'external_reference'), name='uq_sft_lead_ext_ref'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='created_by_user',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to='tenant_core.tenantuser'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, db_column='in_reply_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='tenant_core.communicationmessage'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='lead',
            field=models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='tenant_core.lead'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='tenant_core.organization'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='related_followup',
            field=models.ForeignKey(blank=True, db_column='related_followup_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='tenant_core.salesfollowuptask'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='related_trial',
            field=models.ForeignKey(blank=True, db_column='related_trial_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='tenant_core.trialbooking'),
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_communications', to='tenant_core.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='communicationstatusevent',
            name='message',
            field=models.ForeignKey(db_column='message_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='tenant_core.communicationmessage'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['organization', 'channel', 'status'], name='idx_comm_org_chan_stat'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['lead', 'created_at'], name='idx_comm_lead_created'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['provider', 'provider_message_id'], name='idx_comm_prov_msg_id'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['organization', 'trigger_type'], name='idx_comm_org_trigger'),
        ),
        migrations.AddConstraint(
            model_name='communicationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('organization', 'idempotency_key'), name='uq_comm_org_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='communicationstatusevent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id__isnull', False)), fields=('message', 'provider_event_id'), name='uq_comm_stat_msg_event'),
        ),
    ]
