# Generated by Django 5.2.3 on 2026-09-21 13:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0037_phase5_communication_and_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('domain', models.CharField(default='crm', help_text='Domain grouping e.g. crm, commerce, etc.', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to='tenant_core.tenantuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_workflows', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'automation_workflows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationWorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('trigger_type', models.CharField(help_text='Canonical trigger code e.g. LEAD_CREATED', max_length=100)),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Trigger-level filters/conditions')),
                ('steps_definition', models.JSONField(default=list, help_text='Ordered/graph step definitions')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_workflow_versions', to='tenant_core.tenantuser')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenant_core.automationworkflow')),
            ],
            options={
                'db_table': 'automation_workflow_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='automationworkflow',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_workflow', to='tenant_core.automationworkflowversion'),
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event_type', models.CharField(max_length=100)),
                ('trigger_event_id', models.UUIDField(help_text='DomainOutboxEvent id or unique idempotency UUID')),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('current_step_id', models.CharField(blank=True, default='', max_length=100)),
                ('waiting_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('execution_depth', models.PositiveIntegerField(default=0, help_text='Tracks chain depth for recursion prevention')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_executions', to='tenant_core.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='tenant_core.automationworkflow')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='tenant_core.automationworkflowversion')),
            ],
            options={
                'db_table': 'automation_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=100)),
                ('step_type', models.CharField(choices=[('ACTION', 'Action'), ('CONDITION', 'Condition'), ('WAIT', 'Wait'), ('END', 'End')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('resume_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='tenant_core.automationexecution')),
            ],
            options={
                'db_table': 'automation_step_executions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['execution', 'step_id'], name='idx_step_exec_lookup')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'step_id', 'attempt_count'), name='uq_step_exec_attempt')],
            },
        ),
        migrations.AddIndex(
            model_name='automationworkflowversion',
            index=models.Index(fields=['workflow', 'status'], name='idx_wfv_wf_status'),
        ),
        migrations.AddIndex(
            model_name='automationworkflowversion',
            index=models.Index(fields=['trigger_type', 'status'], name='idx_wfv_trig_status'),
        ),
        migrations.AlterUniqueTogether(
            name='automationworkflowversion',
            unique_together={('workflow', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='automationworkflow',
            index=models.Index(fields=['organization', 'status'], name='idx_wf_org_status'),
        ),
        migrations.AddIndex(
            model_name='automationworkflow',
            index=models.Index(fields=['domain'], name='idx_wf_domain'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status', 'waiting_until'], name='idx_auto_exec_wait'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='idx_auto_exec_agg'),
        ),
        migrations.AddConstraint(
            model_name='automationexecution',
            constraint=models.UniqueConstraint(fields=('organization', 'workflow_version', 'trigger_event_id'), name='uq_auto_exec_evt'),
        ),
    ]
