# Generated by Django 5.2.3 on 2026-09-22 06:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0038_phase6_automation_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMAttentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch to activate attention reason calculations for this organization.')),
                ('sla_breach_attention_enabled', models.BooleanField(default=False, help_text='Flag leads whose stage SLA has breached according to CRMStageSlaPolicy.')),
                ('no_followup_attention_enabled', models.BooleanField(default=False, help_text='Flag leads with no scheduled follow-up after the applicable stage SLA deadline.')),
                ('overdue_followup_attention_enabled', models.BooleanField(default=False, help_text='Flag leads whose pending follow-up task has passed its due_at deadline.')),
                ('no_response_attention_enabled', models.BooleanField(default=False, help_text='Flag leads with outbound communications awaiting inbound response beyond the configured window.')),
                ('no_response_wait_hours', models.PositiveIntegerField(blank=True, help_text='Hours to wait after outbound communication before flagging no response. Nullable until configured.', null=True)),
                ('trial_not_booked_attention_enabled', models.BooleanField(default=False, help_text='Flag trial-eligible leads without a booked trial after stage SLA deadline.')),
                ('trial_confirmation_attention_enabled', models.BooleanField(default=False, help_text='Flag trials in pending confirmation beyond the configured wait duration.')),
                ('trial_no_show_attention_enabled', models.BooleanField(default=False, help_text='Flag trial no-shows without a completed recovery follow-up.')),
                ('post_trial_followup_attention_enabled', models.BooleanField(default=False, help_text='Flag attended trials without a post-trial sales consultation follow-up.')),
                ('unassigned_lead_attention_enabled', models.BooleanField(default=False, help_text='Flag leads that have no active assigned sales agent.')),
                ('unassigned_wait_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes after intake before an unassigned lead is flagged. Nullable until configured.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='crm_attention_policy', to='tenant_core.organization')),
            ],
            options={
                'verbose_name': 'CRM Attention Policy',
                'verbose_name_plural': 'CRM Attention Policies',
                'db_table': 'crm_attention_policies',
            },
        ),
    ]
