# Generated by Django 5.2.17 on 2026-09-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0035_attendancerecord_face_verified_and_more'),
        ('tenant_core', '0040_crm_agent_assignment_config'),
    ]

    operations = [
    ]
