# Generated by Django 5.2.3 on 2026-09-26 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_program_branch_availabilities(apps, schema_editor):
    from config.routers import set_tenant_db_alias, get_tenant_db_alias
    db_alias = schema_editor.connection.alias
    prev_alias = get_tenant_db_alias()
    set_tenant_db_alias(db_alias)
    try:
        Program = apps.get_model('tenant_core', 'Program')
        Branch = apps.get_model('tenant_core', 'Branch')
        ProgramBranchAvailability = apps.get_model('tenant_core', 'ProgramBranchAvailability')

        programs = Program.objects.using(db_alias).filter(status='ACTIVE')
        for prog in programs:
            branches = Branch.objects.using(db_alias).filter(organization_id=prog.organization_id, status='ACTIVE')
            for br in branches:
                if not ProgramBranchAvailability.objects.using(db_alias).filter(program_id=prog.id, branch_id=br.id).exists():
                    ProgramBranchAvailability.objects.using(db_alias).create(
                        program_id=prog.id,
                        branch_id=br.id,
                        is_active=True
                    )
    finally:
        set_tenant_db_alias(prev_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0043_lead_assignment_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBranchAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'program_branch_availabilities',
            },
        ),
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='program',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('GROUP', 'Group Studio'), ('PERSONAL_TRAINING', 'Personal Training'), ('OPEN_GYM', 'Open Gym Access'), ('HYBRID', 'Hybrid / Online')], default='GROUP', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='tenant_core.organization'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='tenant_core.tenantuser'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['organization', 'display_order'], name='idx_prog_org_order'),
        ),
        migrations.AddField(
            model_name='programbranchavailability',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_availabilities', to='tenant_core.branch'),
        ),
        migrations.AddField(
            model_name='programbranchavailability',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_availabilities', to='tenant_core.program'),
        ),
        migrations.AddIndex(
            model_name='programbranchavailability',
            index=models.Index(fields=['branch', 'is_active'], name='idx_progbr_avail_br_act'),
        ),
        migrations.AddIndex(
            model_name='programbranchavailability',
            index=models.Index(fields=['program', 'is_active'], name='idx_progbr_avail_pr_act'),
        ),
        migrations.AlterUniqueTogether(
            name='programbranchavailability',
            unique_together={('program', 'branch')},
        ),
        migrations.RunPython(
            backfill_program_branch_availabilities,
            reverse_code=migrations.RunPython.noop
        ),
    ]
