# Generated by Django 5.2.3 on 2026-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0045_program_category_backfill_and_delivery_mode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='packageversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('package',), name='chk_single_active_package_version_per_package'),
        ),
    ]
