# Generated by Django 5.2.3 on 2026-09-29 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0046_package_version_single_active_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'In-App Notification', 'verbose_name_plural': 'In-App Notifications'},
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_response_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='response_sla_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('BREACHED', 'Breached')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CRMStageAutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(choices=[('FOLLOWUP_COMPLETED', 'Follow-up Task Completed'), ('TRIAL_BOOKED', 'Trial Session Booked'), ('TRIAL_RESCHEDULED', 'Trial Session Rescheduled'), ('TRIAL_ATTENDED', 'Trial Session Attended'), ('TRIAL_NO_SHOW', 'Trial Session Marked No-Show'), ('TRIAL_CANCELLED', 'Trial Session Cancelled'), ('LEAD_CONVERTED', 'Lead Converted to Member')], max_length=50)),
                ('from_stage', models.CharField(default='ANY', help_text="Source stage code e.g. 'NEW_LEAD' or 'ANY'", max_length=50)),
                ('to_stage', models.CharField(choices=[('NEW_LEAD', 'New Lead'), ('TRIAL_BOOKED', 'Trial Booked'), ('TRIAL_CONFIRMED', 'Trial Confirmed'), ('TRIAL_ATTENDED', 'Trial Attended'), ('NO_SHOW', 'No Show'), ('FOLLOW_UP_PENDING', 'Follow-up Pending'), ('INTERESTED', 'Interested'), ('HOT_LEAD', 'Hot Lead'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], help_text="Target stage code e.g. 'INTERESTED'", max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Optional conditions e.g. {'task_types': ['CALL'], 'positive_outcome_only': True, 'outcome_keywords': ['interested', 'trial', 'proceed']}")),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='crm_stage_automation_rules', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_stage_automation_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
