# Generated by Django 5.1.15 on 2026-10-01 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0047_alter_inappnotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLeadImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='SIMULATOR', editable=False, max_length=20)),
                ('page_id', models.CharField(max_length=100)),
                ('form_id', models.CharField(max_length=100)),
                ('external_lead_id', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('field_data', models.JSONField(default=list)),
                ('mapping_snapshot', models.JSONField(default=dict)),
                ('mapping_version', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IMPORTED', 'Imported'), ('NEEDS_MAPPING', 'Needs mapping'), ('NEEDS_ASSIGNMENT', 'Needs branch assignment'), ('NEEDS_REVIEW', 'Repeat enquiry review'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_core.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_meta_lead_imports',
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status', '-received_at'], name='meta_import_org_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'mode', 'external_lead_id'), name='uq_meta_import_org_mode_ext')],
            },
        ),
        migrations.CreateModel(
            name='MetaLeadMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(max_length=100)),
                ('form_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('field_mappings', models.JSONField(default=dict)),
                ('branch_mode', models.CharField(choices=[('FIXED', 'Fixed branch'), ('ANSWER', 'Form answer')], default='FIXED', max_length=10)),
                ('branch_field', models.CharField(blank=True, default='', max_length=100)),
                ('branch_answers', models.JSONField(default=dict)),
                ('repeat_policy', models.CharField(choices=[('REVIEW', 'Hold for review'), ('CREATE_NEW', 'Create a new enquiry')], default='REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_core.branch')),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_core.leadsource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant_core.organization')),
            ],
            options={
                'db_table': 'crm_meta_lead_mappings',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'page_id', 'form_id'), name='uq_meta_mapping_org_page_form')],
            },
        ),
    ]
