# Generated by Django 5.2.3 on 2026-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0050_meta_connection_and_live_imports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaleadimport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IMPORTED', 'Imported'), ('NEEDS_MAPPING', 'Needs mapping'), ('NEEDS_ASSIGNMENT', 'Needs branch assignment'), ('NEEDS_REVIEW', 'Repeat enquiry review'), ('RESOLVED', 'Resolved'), ('FAILED', 'Failed')], default='PENDING', max_length=30),
        ),
    ]
