# Generated by Django 5.2.17 on 2026-10-06 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0051_alter_metaleadimport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('resistance_springs', models.TextField(blank=True, null=True)),
                ('breathing_notes', models.TextField(blank=True, null=True)),
                ('regression_text', models.TextField(blank=True, null=True)),
                ('regression_url', models.TextField(blank=True, null=True)),
                ('video_provider', models.CharField(blank=True, choices=[('UPLOAD', 'Direct Upload'), ('GOOGLE_DRIVE', 'Google Drive'), ('YOUTUBE', 'YouTube'), ('ZATA', 'Zata Storage'), ('EXTERNAL', 'External URL')], max_length=30, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('private_video_url', models.TextField(blank=True, null=True)),
                ('video_storage_path', models.TextField(blank=True, null=True)),
                ('video_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file_size', models.BigIntegerField(blank=True, null=True)),
                ('video_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('video_download_status', models.CharField(choices=[('NONE', 'No Video'), ('PENDING', 'Pending Download'), ('DOWNLOADING', 'Downloading'), ('COMPLETED', 'Stored / Ready'), ('FAILED', 'Download Failed')], default='NONE', max_length=30)),
                ('video_download_error', models.TextField(blank=True, null=True)),
                ('video_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('folder_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cue_1', models.TextField(blank=True, null=True)),
                ('cue_2', models.TextField(blank=True, null=True)),
                ('cue_3', models.TextField(blank=True, null=True)),
                ('shot_by', models.CharField(blank=True, max_length=150, null=True)),
                ('shot_date', models.DateField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=150, null=True)),
                ('edit_date', models.DateField(blank=True, null=True)),
                ('edit_checked', models.BooleanField(default=False)),
                ('requirement_cut', models.TextField(blank=True, null=True)),
                ('youtube_public', models.BooleanField(default=False)),
                ('reference_shoot_url', models.TextField(blank=True, null=True)),
                ('content_kind', models.CharField(choices=[('MOVEMENT', 'Movement'), ('SETUP', 'Setup'), ('INSTRUCTION', 'Instruction'), ('TECHNIQUE', 'Technique'), ('OTHER', 'Other')], default='MOVEMENT', max_length=30)),
                ('is_wod_eligible', models.BooleanField(default=False)),
                ('classification_status', models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('NEEDS_REVIEW', 'Needs Review')], default='INCOMPLETE', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('raw_import_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='workout_content_items', to='tenant_core.organization')),
                ('video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wod_content_items', to='tenant_core.file')),
            ],
            options={
                'db_table': 'workout_content_items',
                'ordering': ['movement_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_group', models.CharField(choices=[('PROGRAM', 'Program / Class Type'), ('SECTION', 'Workout Section'), ('USER_LEVEL', 'User Level'), ('INTENSITY', 'Intensity Level'), ('MUSCLE_GROUP', 'Muscle Group'), ('BODY_TARGET', 'Body Target'), ('BREATHING', 'Breathing Pattern'), ('EQUIPMENT', 'Equipment'), ('MOVEMENT_FAMILY', 'Movement Family')], max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='workout_tags', to='tenant_core.organization')),
            ],
            options={
                'db_table': 'workout_tags',
                'ordering': ['tag_group', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutContentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(db_column='content_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='tenant_core.workoutcontentitem')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='workout_content_tags', to='tenant_core.organization')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_tags', to='tenant_core.workouttag')),
            ],
            options={
                'db_table': 'workout_content_tags',
                'ordering': ['tag__tag_group', 'tag__display_order', 'tag__name'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutcontentitem',
            index=models.Index(fields=['organization', 'status'], name='idx_wod_item_org_status'),
        ),
        migrations.AddIndex(
            model_name='workoutcontentitem',
            index=models.Index(fields=['organization', 'content_kind'], name='idx_wod_item_org_kind'),
        ),
        migrations.AddIndex(
            model_name='workoutcontentitem',
            index=models.Index(fields=['organization', 'is_wod_eligible'], name='idx_wod_item_org_elig'),
        ),
        migrations.AddIndex(
            model_name='workoutcontentitem',
            index=models.Index(fields=['organization', 'classification_status'], name='idx_wod_item_org_class'),
        ),
        migrations.AddIndex(
            model_name='workouttag',
            index=models.Index(fields=['organization', 'tag_group', 'status'], name='idx_wod_tag_org_grp_st'),
        ),
        migrations.AddConstraint(
            model_name='workouttag',
            constraint=models.UniqueConstraint(fields=('organization', 'tag_group', 'code'), name='uq_workout_tag_org_group_code'),
        ),
        migrations.AddIndex(
            model_name='workoutcontenttag',
            index=models.Index(fields=['organization', 'tag'], name='idx_wod_ctag_org_tag'),
        ),
        migrations.AddIndex(
            model_name='workoutcontenttag',
            index=models.Index(fields=['content_item', 'tag'], name='idx_wod_ctag_item_tag'),
        ),
        migrations.AddConstraint(
            model_name='workoutcontenttag',
            constraint=models.UniqueConstraint(fields=('content_item', 'tag'), name='uq_workout_content_item_tag'),
        ),
    ]
