# Generated by Django 5.2.3 on 2026-10-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0052_intakeform_agreement_text_intakeform_agreement_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesubmission',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='signer_identity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='signer_ip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='signer_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='parq_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='parq_form',
            field=models.ForeignKey(blank=True, db_column='parq_form_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_memberships', to='tenant_core.intakeform'),
        ),
        migrations.AddField(
            model_name='membership',
            name='parq_status',
            field=models.CharField(choices=[('PENDING', 'Pending Signature'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='parq_submission',
            field=models.ForeignKey(blank=True, db_column='parq_submission_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfied_memberships', to='tenant_core.intakesubmission'),
        ),
    ]
