# Generated by Django 5.1.15 on 2026-10-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_core', '0052_wod_content_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='agreement_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='agreement_title',
            field=models.CharField(blank=True, default='Physical Activity Readiness & Assumption of Risk Agreement', max_length=255),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='assigned_programs',
            field=models.ManyToManyField(blank=True, related_name='assigned_intake_forms', to='tenant_core.program'),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='is_default_for_all_programs',
            field=models.BooleanField(default=True, help_text='If True, applies as default PAR-Q to all programs unless explicitly overridden'),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='is_required_for_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='reassessment_days',
            field=models.IntegerField(default=365, help_text='Number of days a submission remains valid before requiring reassessment'),
        ),
        migrations.AddField(
            model_name='intakeform',
            name='requires_explicit_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='agreement_text_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='form_snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='membership',
            field=models.ForeignKey(blank=True, db_column='membership_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='tenant_core.membership'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='tenant_core.order'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='program',
            field=models.ForeignKey(blank=True, db_column='program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='tenant_core.program'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=30),
        ),
    ]
