# Generated by Django 5.2.3 on 2026-09-11 20:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_control_plane_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditevent',
            name='resource_id',
            field=models.UUIDField(blank=True, help_text='UUID of affected resource', null=True),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='key',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='value',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='code',
            field=models.CharField(help_text='e.g. ACTIVE_MEMBERS, STORAGE_GB, AI_MINUTES', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcemetric',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='saasplanresourcelimit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='saasplanresourcelimit',
            name='limit_value',
            field=models.DecimalField(decimal_places=4, default=-1, help_text='-1 = unlimited', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saasplanresourcelimit',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.resourcemetric'),
        ),
        migrations.AlterField(
            model_name='saasplanresourcelimit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resource_limits', to='master.saasplan'),
        ),
        migrations.AlterField(
            model_name='saasplanresourcelimit',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenantdatahostingpolicy',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='hosting_policy', to='master.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantdatasource',
            name='database_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='tenantdatasource',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Provisioning'), ('PROVISIONING', 'Provisioning in Progress'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FAILED', 'Provisioning Failed'), ('DECOMMISSIONED', 'Decommissioned')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantdatasource',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='data_source', to='master.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantresourcelimit',
            name='limit_value',
            field=models.DecimalField(decimal_places=4, default=-1, help_text='-1 = unlimited', max_digits=20),
        ),
        migrations.AlterField(
            model_name='tenantresourcelimit',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.resourcemetric'),
        ),
        migrations.AlterField(
            model_name='tenantresourcelimit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resource_limits', to='master.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantresourceusage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenantresourceusage',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tenantresourceusage',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.resourcemetric'),
        ),
        migrations.AlterField(
            model_name='tenantresourceusage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resource_usage', to='master.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantusagealert',
            name='current_pct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenantusagealert',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='master.resourcemetric'),
        ),
        migrations.AlterField(
            model_name='tenantusagealert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantusagealert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usage_alerts', to='master.tenant'),
        ),
        migrations.AlterField(
            model_name='tenantusagealert',
            name='threshold_pct',
            field=models.IntegerField(default=80),
        ),
    ]
