# Generated by Django 5.2.3 on 2026-09-17 07:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_sprint15_master_branding_and_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AuthenticationIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lookup_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('identifier_type', models.CharField(choices=[('EMAIL', 'Email Address'), ('USERNAME', 'Username')], default='EMAIL', max_length=20)),
                ('identifier', models.CharField(db_index=True, max_length=320)),
                ('account_type', models.CharField(choices=[('PLATFORM', 'Platform User'), ('TENANT', 'Tenant User')], max_length=20)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authentication_identities',
                'indexes': [models.Index(fields=['lookup_hash'], name='idx_auth_ident_hash'), models.Index(fields=['account_type', 'subject_id'], name='idx_auth_ident_subj'), models.Index(fields=['tenant_id', 'status'], name='idx_auth_ident_tenant'), models.Index(fields=['identifier'], name='idx_auth_ident_val')],
            },
        ),
    ]
