# Generated by Django 5.2.17 on 2026-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_platformuser_username_authenticationidentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationidentity',
            name='lookup_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='authenticationidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'PLATFORM')), fields=('lookup_hash',), name='auth_platform_identifier_unique'),
        ),
        migrations.AddConstraint(
            model_name='authenticationidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'TENANT')), fields=('tenant_id', 'lookup_hash'), name='auth_tenant_identifier_unique'),
        ),
    ]
