# Generated by Django 5.1.15 on 2026-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_scope_login_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='email_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='remove_watermark',
            field=models.BooleanField(default=False),
        ),
    ]
